// @versione 2026-09-10.3 | database_panoceania.js | proprieta`: chat DATABASE
// ==========================================
// --- database_panoceania.js ---
// Database Unità PanOceania (da lista ufficiale "allpano", N5.2)
// Nomi skill/equip allineati al catalogo_n5.js (nomi canonici).
// Trascrizione manuale dalle schede PDF: possibili refusi su singole
// statistiche/armi di varianti specifiche, da correggere in collaudo.
// ==========================================

window.DB_PANOCEANIA = [
    // ===== GROUP 1: Fusilier =====
    { id: "fusilier_cr", nome: "Fusilier (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "fusilier_hmg", nome: "Fusilier (Heavy Machine Gun)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "fusilier_ml", nome: "Fusilier (Missile Launcher)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Missile Launcher", equip: "Pistol, CC Weapon" },
    { id: "fusilier_sniper", nome: "Fusilier (MULTI Sniper Rifle)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "MULTI Sniper Rifle", equip: "Pistol, CC Weapon" },
    { id: "fusilier_hacker", nome: "Fusilier (Hacker, Hacking Device)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker", weapon: "Combi Rifle", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "fusilier_fo", nome: "Fusilier (Forward Observer)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Forward Observer", weapon: "Combi Rifle, Flash Pulse", equip: "Deployable Repeater, Pistol, CC Weapon" },
    { id: "fusilier_lt1", nome: "Fusilier (Lieutenant)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Lieutenant", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "fusilier_lt2", nome: "Fusilier (Lieutenant, variante 2)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Lieutenant", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "fusilier_paramedic", nome: "Fusilier (Paramedic)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Paramedic", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },
    { id: "fusilier_specops", nome: "Fusilier (Commlink [+1], Specialist Operative)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Specialist Operative", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },

    // ===== GROUP 2: Nisse, Bolt =====
    { id: "nisse_hmg", nome: "Nisse (Heavy Machine Gun)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 12, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Climb (3\"), Mimetism (-3), Terrain (Total)", weapon: "Heavy Machine Gun", equip: "Multispectral Visor L2, Boarding Pistol, CC Weapon" },
    { id: "nisse_sniper", nome: "Nisse (MULTI Sniper Rifle)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 12, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Climb (3\"), Mimetism (-3), Terrain (Total)", weapon: "MULTI Sniper Rifle", equip: "Multispectral Visor L2, Boarding Pistol, CC Weapon" },
    { id: "nisse_hacker", nome: "Nisse (Hacker, Hacking Device)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 12, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Hacker, Climb (3\"), Mimetism (-3), Terrain (Total)", weapon: "Combi Rifle, Light Shotgun", equip: "Multispectral Visor L2, Boarding Pistol, CC Weapon" },
    { id: "nisse_paramedic", nome: "Nisse (Paramedic)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 12, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Paramedic, Climb (3\"), Mimetism (-3), Terrain (Total)", weapon: "Combi Rifle, Light Shotgun", equip: "Multispectral Visor L2, MediKit, Boarding Pistol, CC Weapon" },
    { id: "bolt_combi", nome: "Bolt (Combi Rifle, Light Shotgun)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Combi Rifle, Light Shotgun, Drop Bears", equip: "Pistol, CC Weapon" },
    { id: "bolt_bsg", nome: "Bolt (Boarding Shotgun)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Boarding Shotgun(+1B), Drop Bears", equip: "Pistol, CC Weapon" },
    { id: "bolt_ml", nome: "Bolt (Missile Launcher)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Missile Launcher", equip: "Pistol, CC Weapon" },
    { id: "bolt_spitfire", nome: "Bolt (Spitfire)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Spitfire", equip: "Pistol, CC Weapon" },
    { id: "bolt_cmd", nome: "Bolt (Chain of Command)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Chain of Command, Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Combi Rifle, Light Shotgun, Drop Bears", equip: "Pistol, CC Weapon" },
    { id: "bolt_hacker", nome: "Bolt (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Hacker, Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Boarding Shotgun(+1B), E/M Mine", equip: "Hacking Device, Pistol, CC Weapon" },

    // ===== GROUP 3: Bolt, Orc =====
    { id: "bolt_khacker", nome: "Bolt (Hacker, Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Hacker, Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Boarding Shotgun(+1B), E/M Mine", equip: "Killer Hacking Device, Pistol, CC Weapon" },
    { id: "bolt_paramedic", nome: "Bolt (Paramedic)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Paramedic, Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Combi Rifle, Light Shotgun, Drop Bears", equip: "MediKit, Pistol, CC Weapon" },
    { id: "bolt_msv1", nome: "Bolt (Multispectral Visor L1)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "MULTI Sniper Rifle", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "bolt_lt", nome: "Bolt (Lieutenant)", tipo: "MI", mov: "4-4", cc: 16, bs: 13, ph: 11, wip: 12, arm: 2, bts: 6, w: 1, s: 2, skills: "Lieutenant, Immunity (Shock), Marksmanship, Terrain (Total), Warhorse", weapon: "Combi Rifle, Light Shotgun, Drop Bears", equip: "Pistol, CC Weapon" },
    { id: "orc_multi", nome: "Orc (MULTI Rifle)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Immunity (Shock)", weapon: "MULTI Rifle", equip: "Pistol, CC Weapon" },
    { id: "orc_firewall", nome: "Orc (TinBot: Firewall)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Immunity (Shock)", weapon: "MULTI Rifle", equip: "TinBot: Firewall (-3), Pistol, CC Weapon" },
    { id: "orc_hmg", nome: "Orc (Heavy Machine Gun)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Immunity (Shock)", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "orc_bsg", nome: "Orc (Boarding Shotgun)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Immunity (Shock)", weapon: "Boarding Shotgun(+1B)", equip: "Pistol, CC Weapon" },
    { id: "orc_hacker", nome: "Orc (Hacker, Hacking Device)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Hacker, Immunity (Shock)", weapon: "MULTI Rifle", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "orc_lt1", nome: "Orc (Lieutenant, MULTI Rifle)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Lieutenant, Immunity (Shock)", weapon: "MULTI Rifle", equip: "Pistol, CC Weapon" },

    // ===== GROUP 4: Orc, Aquila, Aquila FTO, Swiss Guard, Cutter, Crabbot =====
    { id: "orc_lt2", nome: "Orc (Lieutenant, Heavy Machine Gun)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Lieutenant, Immunity (Shock)", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "orc_feuerbach", nome: "Orc (Feuerbach)", tipo: "HI", mov: "6-2", cc: 15, bs: 14, ph: 14, wip: 12, arm: 4, bts: 3, w: 2, s: 2, skills: "Immunity (Shock)", weapon: "Feuerbach", equip: "Pistol, CC Weapon" },
    { id: "aquila", nome: "Aquila", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 6, bts: 2, w: 2, s: 2, skills: "Immunity (Shock), Jump (3\")", weapon: "Heavy Machine Gun", equip: "Multispectral Visor L3, Pistol, Shock CC Weapon" },
    { id: "aquila_fto_specops", nome: "Aquila FTO (Specialist Operative)", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 6, bts: 2, w: 2, s: 2, skills: "Specialist Operative, Immunity (Shock), Jump (3\")", weapon: "MULTI Marksman Rifle, Disco Baller", equip: "Multispectral Visor L3, Pistol, Shock CC Weapon" },
    { id: "aquila_fto_lt", nome: "Aquila FTO (Lieutenant, Specialist Operative)", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 6, bts: 2, w: 2, s: 2, skills: "Lieutenant, Specialist Operative, Immunity (Shock), Jump (3\")", weapon: "MULTI Marksman Rifle, Disco Baller", equip: "Multispectral Visor L3, Pistol, Shock CC Weapon" },
    { id: "swissguard_hmg", nome: "Swiss Guard (Heavy Machine Gun, Pulzar)", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Camouflage, Hidden Deployment, Immunity (Shock), Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "Heavy Machine Gun, Pulzar", equip: "Heavy Pistol, AP CC Weapon(PS=6)", deployState: "CAMO", state: "CAMO" },
    { id: "swissguard_ml", nome: "Swiss Guard (Missile Launcher, Light Shotgun)", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Camouflage, Hidden Deployment, Immunity (Shock), Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "Missile Launcher, Light Shotgun", equip: "Heavy Pistol, AP CC Weapon(PS=6)", deployState: "CAMO", state: "CAMO" },
    { id: "swissguard_hacker", nome: "Swiss Guard (Hacker, Hacking Device, X Visor)", tipo: "HI", mov: "4-4", cc: 15, bs: 15, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Hacker, Camouflage, Hidden Deployment, Immunity (Shock), Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "MULTI Rifle, Pulzar", equip: "X Visor, Hacking Device, Heavy Pistol, AP CC Weapon(PS=6)", deployState: "CAMO", state: "CAMO" },
    { id: "cutter_nco", nome: "Cutter (NCO)", tipo: "TAG", mov: "6-4", cc: 18, bs: 15, ph: 15, wip: 12, arm: 8, bts: 6, str: 3, s: 7, skills: "NCO, BS Attack (SR-1), Camouflage, Courage, Dodge (PH=11), Gizmokit (PH=13), Hidden Deployment, Mimetism (-6), Remote Presence, Surprise Attack (-3), Terrain (Aquatic)", weapon: "MULTI Heavy Machine Gun", equip: "ECM (Guided -6), CC Weapon(PS=5)" },
    { id: "crabbot", nome: "Crabbot (REM)", tipo: "REM", mov: "6-4", cc: 0, bs: 0, ph: 10, wip: 12, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Dodge (+3), Mimetism (-3), Peripheral (Ancillary), Specialist Operative, Terrain (Aquatic)", weapon: "-", equip: "-" },

    // ===== GROUP 5: Cutter, Crabbot, Croc Man, Trauma-Doc, Machinist =====
    { id: "cutter_lt", nome: "Cutter (Lieutenant)", tipo: "TAG", mov: "6-4", cc: 18, bs: 15, ph: 15, wip: 12, arm: 8, bts: 6, str: 3, s: 7, skills: "Lieutenant, BS Attack (SR-1), Camouflage, Courage, Dodge (PH=11), Gizmokit (PH=13), Hidden Deployment, Mimetism (-6), Remote Presence, Surprise Attack (-3), Terrain (Aquatic)", weapon: "MULTI Heavy Machine Gun", equip: "ECM (Guided -6), CC Weapon(PS=5)" },
    { id: "crocman_base", nome: "Croc Man (Boarding Shotgun, Shock Mine)", tipo: "SK", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Shock Mine, D-Charges", equip: "X Visor, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "crocman_hacker", nome: "Croc Man (Hacker, Hacking Device)", tipo: "SK", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, D-Charges", equip: "X Visor, Hacking Device, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "crocman_sniper", nome: "Croc Man (MULTI Sniper Rifle)", tipo: "SK", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "MULTI Sniper Rifle, Shock Mine", equip: "X Visor, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "crocman_fo", nome: "Croc Man (Forward Observer)", tipo: "SK", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Forward Observer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Flash Pulse, D-Charges, Shock Mine", equip: "X Visor, Deployable Repeater, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "crocman_minelayer", nome: "Croc Man (Minelayer)", tipo: "SK", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Minelayer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, D-Charges, Shock Mine", equip: "X Visor, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "traumadoc", nome: "Trauma-Doc", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Doctor", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },
    { id: "machinist_dcharges", nome: "Machinist (D-Charges)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer", weapon: "Combi Rifle, D-Charges", equip: "Deactivator, GizmoKit, Pistol, CC Weapon" },
    { id: "machinist_turret", nome: "Machinist (Armed Turret Combi R.)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer", weapon: "Combi Rifle, D-Charges, Armed Turret (Combi Rifle)", equip: "Deactivator, GizmoKit, Pistol, CC Weapon" },

    // ===== GROUP 6: Pathfinder Dronbot, Sierra Dronbot, Clipper Dronbot, Fugazi Dronbot, Joan of Arc =====
    { id: "pathfinder_dronbot", nome: "Pathfinder Dronbot", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Forward Observer, Remote Presence, Sensor, Triangulated Fire", weapon: "Combi Rifle, Flash Pulse", equip: "Deactivator, Repeater, PARA CC Weapon(-3)" },
    { id: "pathfinder_dronbot_ta", nome: "Pathfinder Dronbot (Tactical Awareness)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Tactical Awareness, Courage, Forward Observer, Remote Presence, Sensor, Triangulated Fire", weapon: "Combi Rifle, Flash Pulse", equip: "Deactivator, Repeater, PARA CC Weapon(-3)" },
    { id: "sierra_dronbot_hmg", nome: "Sierra Dronbot (Heavy Machine Gun)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Remote Presence, Total Reaction", weapon: "Heavy Machine Gun", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "sierra_dronbot_thunderbolt", nome: "Sierra Dronbot (Thunderbolt)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Remote Presence, Total Reaction", weapon: "Thunderbolt(+1B)", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "clipper_dronbot", nome: "Clipper Dronbot (BS Attack [Guided])", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Remote Presence", weapon: "Missile Launcher", equip: "PARA CC Weapon(-3)" },
    { id: "clipper_dronbot_fto", nome: "Clipper Dronbot FTO", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Remote Presence", weapon: "Missile Launcher(+1B)", equip: "PARA CC Weapon(-3)" },
    { id: "fugazi_dronbot", nome: "Fugazi Dronbot", tipo: "REM", mov: "6-6", cc: 13, bs: 8, ph: 11, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Mimetism (-3), Remote Presence", weapon: "Flash Pulse", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "joanofarc", nome: "Joan of Arc", tipo: "HI", mov: "4-4", cc: 23, bs: 15, ph: 15, wip: 15, arm: 5, bts: 6, w: 2, s: 2, skills: "BS Attack (SR-1), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "MULTI Rifle, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc_strategic", nome: "Joan of Arc (Strategic Deployment)", tipo: "HI", mov: "4-4", cc: 23, bs: 15, ph: 15, wip: 15, arm: 5, bts: 6, w: 2, s: 2, skills: "Strategic Deployment, BS Attack (SR-1), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "MULTI Rifle, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc_lt", nome: "Joan of Arc (Lieutenant)", tipo: "HI", mov: "4-4", cc: 23, bs: 15, ph: 15, wip: 15, arm: 5, bts: 6, w: 2, s: 2, skills: "Lieutenant, BS Attack (SR-1), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "MULTI Rifle, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },

    // ===== GROUP 7: Joan of Arc, Teutonic Knight, Tikbalang, Crabbot =====
    { id: "joanofarc_lt_token", nome: "Joan of Arc (Lieutenant [+1 Command Token])", tipo: "HI", mov: "4-4", cc: 23, bs: 15, ph: 15, wip: 15, arm: 5, bts: 6, w: 2, s: 2, skills: "Lieutenant, BS Attack (SR-1), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "MULTI Rifle, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc_lt_strategic", nome: "Joan of Arc (Lieutenant, Strategic Deployment)", tipo: "HI", mov: "4-4", cc: 23, bs: 15, ph: 15, wip: 15, arm: 5, bts: 6, w: 2, s: 2, skills: "Lieutenant, Strategic Deployment, BS Attack (SR-1), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "MULTI Rifle, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "teutonic_ls", nome: "Teutonic Knight (Light Shotgun, Panzerfaust)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Light Shotgun, Panzerfaust", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "teutonic_firewall", nome: "Teutonic Knight (TinBot: Firewall)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Light Shotgun, Panzerfaust", equip: "TinBot: Firewall (-3), Pistol, DA CC Weapon(PS=5)" },
    { id: "teutonic_ml", nome: "Teutonic Knight (Missile Launcher)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Missile Launcher", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "teutonic_specops", nome: "Teutonic Knight (Specialist Operative)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "Specialist Operative, Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Submachine Gun, Panzerfaust", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "teutonic_nco", nome: "Teutonic Knight (NCO)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "NCO, Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Spitfire", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "teutonic_lt", nome: "Teutonic Knight (Lieutenant)", tipo: "HI", mov: "6-2", cc: 22, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, w: 2, s: 2, skills: "Lieutenant, Dodge (+3), Dodge (+1\"), Immunity (Shock), Impetuous, Limited Cover, Martial Arts L2, Religious Troop, Terrain (Jungle)", weapon: "Light Shotgun, Panzerfaust", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "tikbalang", nome: "Tikbalang", tipo: "TAG", mov: "6-4", cc: 17, bs: 15, ph: 15, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "BS Attack (SR-1), Climbing Plus, Courage, Dodge (PH=11), Gizmokit (PH=13), Mimetism (-3), Remote Presence, Tactical Awareness, Terrain (Total)", weapon: "Heavy Machine Gun, Heavy Flamethrower, Shock Mine", equip: "ECM (Guided -6), AP CC Weapon(PS=5)" },
    { id: "tikbalang_lt", nome: "Tikbalang (Lieutenant [+1 Order])", tipo: "TAG", mov: "6-4", cc: 17, bs: 15, ph: 15, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "Lieutenant, BS Attack (SR-1), Climbing Plus, Courage, Dodge (PH=11), Gizmokit (PH=13), Mimetism (-3), Remote Presence, Tactical Awareness, Terrain (Total)", weapon: "Heavy Machine Gun, Heavy Flamethrower, Shock Mine", equip: "ECM (Guided -6), AP CC Weapon(PS=5)" },

    // ===== GROUP 8: Bulleteer, Peacemaker, Auxbot_3, Palbot, Mulebot =====
    { id: "bulleteer_shotgun", nome: "Bulleteer (Heavy Shotgun)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, str: 1, s: 4, skills: "Courage, Mimetism (-6), Remote Presence", weapon: "Heavy Shotgun(+1B)", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "bulleteer_spitfire", nome: "Bulleteer (Spitfire)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, str: 1, s: 4, skills: "Courage, Mimetism (-6), Remote Presence", weapon: "Spitfire", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "peacemaker_pulzar", nome: "Peacemaker (Heavy Shotgun, Pulzar)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, str: 1, s: 4, skills: "Courage, Forward Deployment (+8\"), Mimetism (-3), Remote Presence", weapon: "Heavy Shotgun, Pulzar", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "auxbot3", nome: "Auxbot_3", tipo: "REM", mov: "6-4", cc: 13, bs: 10, ph: 8, wip: 11, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Forward Deployment (+8\"), Mimetism (-3), Peripheral (Synchronized)", weapon: "Heavy Flamethrower, Shock Mine", equip: "PARA CC Weapon(-3)" },
    { id: "auxbot3b_minelayer", nome: "Auxbot_3B (Minelayer)", tipo: "REM", mov: "6-4", cc: 13, bs: 10, ph: 8, wip: 11, arm: 0, bts: 3, str: 1, s: 1, skills: "Minelayer, Courage, Forward Deployment (+8\"), Mimetism (-3), Peripheral (Synchronized)", weapon: "Heavy Flamethrower, Shock Mine", equip: "PARA CC Weapon(-3)" },
    { id: "peacemaker_bsattack", nome: "Peacemaker (BS Attack [+1B])", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, str: 1, s: 4, skills: "Courage, Forward Deployment (+8\"), Mimetism (-3), Remote Presence", weapon: "Boarding Shotgun, Pulzar", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "palbot", nome: "Palbot (REM)", tipo: "REM", mov: "6-4", cc: 11, bs: 8, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Mimetism (-3), Peripheral (Servant)", weapon: "-", equip: "PARA CC Weapon(-3)" },
    { id: "mulebot_hacker", nome: "Mulebot (Hacker, EVO Hacking Device)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Hacker, Courage, Remote Presence", weapon: "-", equip: "Baggage, EVO Hacking Device, PARA CC Weapon(-3)" },
    { id: "mulebot_deactivator", nome: "Mulebot (Deactivator, Repeater)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Courage, Remote Presence", weapon: "-", equip: "Baggage, Deactivator, Repeater, PARA CC Weapon(-3)" },
    { id: "mulebot_totalreaction", nome: "Mulebot (Total Reaction, Repeater)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Total Reaction, Courage, Remote Presence", weapon: "Combi Rifle", equip: "Baggage, Repeater, PARA CC Weapon(-3)" },

    // ===== GROUP 9: Joan of Arc v2, Bipandra, Warcor, Locust =====
    { id: "joanofarc2", nome: "Joan of Arc v2", tipo: "HI", mov: "6-2", cc: 23, bs: 15, ph: 14, wip: 15, arm: 3, bts: 6, w: 2, s: 2, skills: "Dodge (+2\"), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "AP Spitfire, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc2_strategic", nome: "Joan of Arc v2 (Strategic Deployment)", tipo: "HI", mov: "6-2", cc: 23, bs: 15, ph: 14, wip: 15, arm: 3, bts: 6, w: 2, s: 2, skills: "Strategic Deployment, Dodge (+2\"), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "AP Spitfire, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc2_lt", nome: "Joan of Arc v2 (Lieutenant)", tipo: "HI", mov: "6-2", cc: 23, bs: 15, ph: 14, wip: 15, arm: 3, bts: 6, w: 2, s: 2, skills: "Lieutenant, Dodge (+2\"), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "AP Spitfire, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "joanofarc2_lt_token", nome: "Joan of Arc v2 (Lieutenant [+1 Command Token])", tipo: "HI", mov: "6-2", cc: 23, bs: 15, ph: 14, wip: 15, arm: 3, bts: 6, w: 2, s: 2, skills: "Lieutenant, Dodge (+2\"), Frenzy, Immunity (Shock), Inspiring Leadership, Martial Arts L3, No Wound Incapacitation, Number 2, Religious Troop, Stealth, Tactical Awareness", weapon: "AP Spitfire, Pulzar(+1B)", equip: "X Visor, Pistol, EXP CC Weapon(PS=4)" },
    { id: "bipandra", nome: "Bipandra", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Doctor (ReRoll -3), Dodge (+1\"), Immunity (Shock)", weapon: "Combi Rifle, Nanopulser", equip: "MediKit (+1B), Pistol, CC Weapon" },
    { id: "bipandra_ta", nome: "Bipandra (Tactical Awareness)", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Tactical Awareness, Doctor (ReRoll -3), Dodge (+1\"), Immunity (Shock)", weapon: "Combi Rifle, Nanopulser", equip: "MediKit (+1B), Pistol, CC Weapon" },
    { id: "warcor_sixthsense", nome: "Warcor (Sixth Sense)", tipo: "LI", mov: "4-4", cc: 11, bs: 9, ph: 11, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Journalist L1", weapon: "Flash Pulse", equip: "Stun Pistol, PARA CC Weapon(-3)" },
    { id: "locust_bsg", nome: "Locust (Boarding Shotgun)", tipo: "SK", mov: "4-4", cc: 16, bs: 12, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage (1 Use), Climb (3\"), Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Grenades, Drop Bears", equip: "Boarding Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },

    // ===== GROUP 10: Locust, Tech-Bee, Zulu-Cobra, Helot Militiaman FTO =====
    { id: "locust_marksman", nome: "Locust (MULTI Marksman Rifle)", tipo: "SK", mov: "4-4", cc: 16, bs: 12, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage (1 Use), Climb (3\"), Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "MULTI Marksman Rifle", equip: "Boarding Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "locust_hacker", nome: "Locust (Hacker, Hacking Device)", tipo: "SK", mov: "4-4", cc: 16, bs: 12, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage (1 Use), Climb (3\"), Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Breaker Combi Rifle, D-Charges", equip: "Hacking Device, Boarding Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "locust_khacker", nome: "Locust (Hacker, Killer Hacking Device)", tipo: "SK", mov: "4-4", cc: 16, bs: 12, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage (1 Use), Climb (3\"), Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Breaker Combi Rifle, D-Charges", equip: "Killer Hacking Device, Boarding Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "techbee", nome: "Tech-Bee", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Specialist Operative", weapon: "Adhesive Launcher Rifle, Flash Pulse", equip: "Deactivator, GizmoKit, Deployable Repeater, Pistol, PARA CC Weapon(-3)" },
    { id: "zulucobra_spitfire", nome: "Zulu-Cobra (Spitfire)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Spitfire", equip: "Pistol, CC Weapon" },
    { id: "zulucobra_hacker", nome: "Zulu-Cobra (Hacker, Killer Hacking Device)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker, Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Breaker Combi Rifle", equip: "Killer Hacking Device, Pistol, CC Weapon" },
    { id: "zulucobra_sensor", nome: "Zulu-Cobra (Triangulated Fire, Sensor)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Triangulated Fire, Sensor, Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Jammer", equip: "Assault Pistol, CC Weapon" },
    { id: "zulucobra_fo", nome: "Zulu-Cobra (Forward Observer)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Forward Observer, Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Breaker Combi Rifle, Flash Pulse", equip: "Pistol, CC Weapon" },
    { id: "helotmilitiaman_fto_redfury", nome: "Helot Militiaman FTO (Sensor, Shock Marksman Rifle)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Sensor, Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Shock Marksman Rifle", equip: "Pistol, CC Weapon" },

    // ===== GROUP 11: Helot Militiaman FTO, Helot Militiaman, Patsy Garnett, Nøkk =====
    { id: "helotmilitiaman_fto_1", nome: "Helot Militiaman FTO (Sensor, Red Fury)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Sensor, Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Red Fury", equip: "Pistol, CC Weapon" },
    { id: "helotmilitiaman_fto_2", nome: "Helot Militiaman FTO (Sensor, Light Rocket Launcher)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Sensor, Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Submachine Gun, Light Rocket Launcher", equip: "Pistol, CC Weapon" },
    { id: "helotmilitiaman_shock", nome: "Helot Militiaman (Surprise Attack [-3], Camouflage, Shock Marksman Rifle)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage (1 Use), Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Shock Marksman Rifle", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "helotmilitiaman_sniper", nome: "Helot Militiaman (Surprise Attack [-3], Camouflage, MULTI Sniper Rifle)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage (1 Use), Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "MULTI Sniper Rifle", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "helotmilitiaman_redfury", nome: "Helot Militiaman (Surprise Attack [-3], Camouflage, Red Fury)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage (1 Use), Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Red Fury", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "helotmilitiaman_lrl", nome: "Helot Militiaman (Surprise Attack [-3], Camouflage, Light Rocket Launcher)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage (1 Use), Immunity (Shock), Neurocinetics, Stealth, Terrain (Aquatic)", weapon: "Submachine Gun, Light Rocket Launcher", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "patsygarnett", nome: "Patsy Garnett", tipo: "HI", mov: "6-2", cc: 19, bs: 14, ph: 14, wip: 13, arm: 4, bts: 3, w: 2, s: 2, skills: "Forward Observer, FT Master (Helots), Immunity (Shock), NCO, Stealth, Terrain (Total), Warhorse", weapon: "Submachine Gun, E/Mitter, Grenades, D-Charges, Flash Pulse", equip: "Pistol, Shock CC Weapon(PS=6)" },
    { id: "nokk_spitfire", nome: "Nøkk (Spitfire)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Spitfire", equip: "Bangbomb (+4), Pistol, CC Weapon" },
    { id: "nokk_hacker", nome: "Nøkk (Hacker, Hacking Device)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Combi Rifle, Light Shotgun", equip: "Bangbomb (+4), Hacking Device, Pistol, CC Weapon" },
    { id: "nokk_khacker", nome: "Nøkk (Hacker, Killer Hacking Device)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Combi Rifle, Light Shotgun", equip: "Bangbomb (+4), Killer Hacking Device, Pistol, CC Weapon" },

    // ===== GROUP 12: Nøkk, Karhu, Motorized Bounty Hunter =====
    { id: "nokk_minelayer", nome: "Nøkk (Minelayer)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Minelayer, Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Combi Rifle, Light Shotgun, Shock Mine", equip: "Bangbomb (+4), Pistol, CC Weapon" },
    { id: "nokk_fo", nome: "Nøkk (Forward Observer)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Forward Observer, Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Boarding Shotgun(+1B), Panzerfaust, Flash Pulse", equip: "Bangbomb (+4), Pistol, CC Weapon" },
    { id: "nokk_msv1", nome: "Nøkk (Multispectral Visor L1)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Forward Deployment (+8\"), Mimetism (-6), Terrain (Total)", weapon: "Boarding Shotgun(+1B), Panzerfaust", equip: "Bangbomb (+4), Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "karhu_emarat", nome: "Karhu (E/Marat)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 11, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Mimetism (-3), NCO, Terrain (Total)", weapon: "MULTI Rifle, E/Marat, AP Mine", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "karhu_blitzen", nome: "Karhu (Blitzen)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 11, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Mimetism (-3), NCO, Terrain (Total)", weapon: "MULTI Rifle, Blitzen, AP Mine", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "karhu_feuerbach", nome: "Karhu (Feuerbach)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 11, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Mimetism (-3), NCO, Terrain (Total)", weapon: "Feuerbach(+1B), AP Mine", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "karhu_engineer", nome: "Karhu (Engineer, Deactivator)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 11, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Engineer, Climbing Plus, Courage, Mimetism (-3), NCO, Terrain (Total)", weapon: "MULTI Rifle, Blitzen, D-Charges", equip: "Multispectral Visor L1, GizmoKit, Pistol, CC Weapon" },
    { id: "karhu_paramedic", nome: "Karhu (Paramedic)", tipo: "MI", mov: "6-2", cc: 14, bs: 13, ph: 11, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Paramedic, Climbing Plus, Courage, Mimetism (-3), NCO, Terrain (Total)", weapon: "MULTI Rifle, Blitzen, AP Mine", equip: "Multispectral Visor L1, MediKit, Pistol, CC Weapon" },
    { id: "motorizedbountyhunter_riotstopper", nome: "Motorized Bounty Hunter (Heavy Riotstopper)", tipo: "LI", mov: "8-6", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 4, skills: "Booty (ReRoll), Dodge (+2\"), Impetuous, Limited Cover, Mimetism (-3)", weapon: "Boarding Shotgun, Heavy Riotstopper", equip: "Motorcycle, Pistol, PARA CC Weapon(-6)" },
    { id: "motorizedbountyhunter_chaincolt", nome: "Motorized Bounty Hunter (Chain-colt)", tipo: "LI", mov: "8-6", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 4, skills: "Booty (ReRoll), Dodge (+2\"), Impetuous, Limited Cover, Mimetism (-3)", weapon: "Submachine Gun, Chain-colt(+1B)", equip: "Motorcycle, Pistol, PARA CC Weapon(-6)" },

    // ===== GROUP 13: Motorized Bounty Hunter, Squalo Mk-II, Crabbot, Maximus Optime, Operator Maximus, Blocker, Blade FTO =====
    { id: "motorizedbountyhunter_redfury", nome: "Motorized Bounty Hunter (Red Fury)", tipo: "LI", mov: "8-6", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 4, skills: "Booty (ReRoll), Dodge (+2\"), Impetuous, Limited Cover, Mimetism (-3)", weapon: "Red Fury", equip: "Motorcycle, Breaker Pistol, PARA CC Weapon(-6)" },
    { id: "squalomk2_marksman", nome: "Squalo Mk-II (MULTI Marksman Rifle)", tipo: "TAG", mov: "6-4", cc: 18, bs: 15, ph: 15, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "BS Attack (SR-1), Combat Instinct, Courage, Dodge (+1\"), Dodge (PH=11), Gizmokit (PH=13), Remote Presence, Tactical Awareness", weapon: "MULTI Marksman Rifle", equip: "ECM (Guided -6), MULTI Pistol(+1B), CC Weapon(PS=5)" },
    { id: "squalomk2_hmg", nome: "Squalo Mk-II (Heavy Machine Gun, Grenade Launcher)", tipo: "TAG", mov: "6-4", cc: 18, bs: 15, ph: 15, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "BS Attack (SR-1), Combat Instinct, Courage, Dodge (+1\"), Dodge (PH=11), Gizmokit (PH=13), Remote Presence, Tactical Awareness", weapon: "Heavy Machine Gun, Grenade Launcher(PS=6)", equip: "ECM (Guided -6), MULTI Pistol(+1B), CC Weapon(PS=5)" },
    { id: "squalomk2_nco", nome: "Squalo Mk-II (NCO)", tipo: "TAG", mov: "6-4", cc: 18, bs: 15, ph: 15, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "NCO, BS Attack (SR-1), Combat Instinct, Courage, Dodge (+1\"), Dodge (PH=11), Gizmokit (PH=13), Remote Presence, Tactical Awareness", weapon: "MULTI Heavy Machine Gun", equip: "ECM (Guided -6), MULTI Pistol(+1B), CC Weapon(PS=5)" },
    { id: "maximusoptime", nome: "Maximus Optime", tipo: "TAG", mov: "6-4", cc: 24, bs: 14, ph: 13, wip: 13, arm: 6, bts: 6, str: 6, s: 6, skills: "BS Attack (SR-1), CC Attack (-6), Courage, Dodge (+2\"), Immunity (ARM), Immunity (POS), Natural Born Warrior, Tactical Awareness, Transmutation (Escape System -3)", weapon: "Thunderbolt(+2B), E/M Carbine", equip: "ECM (Guided -6), Heavy Pistol, AP+DA CC Weapon(PS=4)" },
    { id: "operatormaximus", nome: "Operator Maximus", tipo: "MI", mov: "6-2", cc: 23, bs: 12, ph: 13, wip: 13, arm: 3, bts: 3, str: 4, s: 2, skills: "CC Attack (-6), Courage, Dodge (+1\"), Immunity (ARM), Natural Born Warrior, Specialist Operative, Tactical Awareness", weapon: "Thunderbolt(+2B), E/M Carbine", equip: "Heavy Pistol, AP+DA CC Weapon(PS=6)" },
    { id: "blocker", nome: "Blocker", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "BS Attack (+1B), Sensor", weapon: "Adhesive Launcher Rifle, Nanopulser, Flash Pulse", equip: "Biometric Visor, X Visor, MULTI Pistol, PARA CC Weapon(-6)" },
    { id: "bladefto", nome: "Blade FTO", tipo: "LI", mov: "4-4", cc: 16, bs: 13, ph: 10, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Immunity (Shock), Mimetism (-3), Stealth, Tactical Awareness, Terrain (Total)", weapon: "Boarding Shotgun, D-Charges", equip: "Silenced Pistol, CC Weapon" },
    { id: "bladefto_engineer", nome: "Blade FTO (Engineer)", tipo: "LI", mov: "4-4", cc: 16, bs: 13, ph: 10, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Engineer, BS Attack (SR-1), Immunity (Shock), Mimetism (-3), Stealth, Tactical Awareness, Terrain (Total)", weapon: "Submachine Gun, D-Charges", equip: "GizmoKit, Silenced Pistol, CC Weapon" },

    // ===== GROUP 14: Blade, Fennec =====
    { id: "blade_decoy", nome: "Blade (Engineer, Forward Deployment [+8\"], Decoy [2])", tipo: "LI", mov: "4-4", cc: 16, bs: 13, ph: 10, wip: 12, arm: 2, bts: 3, w: 1, s: 2, skills: "Engineer, Forward Deployment (+8\"), Decoy (2), BS Attack (SR-1), Immunity (Shock), Mimetism (-3), Stealth, Tactical Awareness, Terrain (Total)", weapon: "Submachine Gun, E/Mitter, D-Charges", equip: "GizmoKit, Silenced Pistol, CC Weapon" },
    { id: "fennec_cr", nome: "Fennec (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Terrain (Desert)", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "fennec_hmg", nome: "Fennec (Heavy Machine Gun)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Terrain (Desert)", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "fennec_ml", nome: "Fennec (Missile Launcher)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Terrain (Desert)", weapon: "Missile Launcher", equip: "Pistol, CC Weapon" },
    { id: "fennec_lrl", nome: "Fennec (Light Rocket Launcher)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Terrain (Desert)", weapon: "Submachine Gun, Light Rocket Launcher", equip: "Pistol, CC Weapon" },
    { id: "fennec_minelayer", nome: "Fennec (Triangulated Fire, Minelayer)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Triangulated Fire, Minelayer, Terrain (Desert)", weapon: "Thunderbolt(+1B), Shock Mine", equip: "Pistol, CC Weapon" },
    { id: "fennec_specops", nome: "Fennec (Commlink [+1], Specialist Operative)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Specialist Operative, Terrain (Desert)", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "fennec_fo", nome: "Fennec (Forward Observer, Sensor)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Forward Observer, Sensor, Terrain (Desert)", weapon: "Combi Rifle, Flash Pulse, Disco Baller", equip: "Pistol, CC Weapon" },
    { id: "fennec_hacker", nome: "Fennec (Hacker, Hacking Device)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Hacker, Terrain (Desert)", weapon: "Submachine Gun, E/Mitter", equip: "FastPanda, Hacking Device, Pistol, CC Weapon" },
    { id: "fennec_paramedic", nome: "Fennec (Paramedic)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Paramedic, Terrain (Desert)", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },

    // ===== GROUP 15: Fennec, Magistrate, Blink =====
    { id: "fennec_lt", nome: "Fennec (Lieutenant)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Lieutenant, Terrain (Desert)", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "magistrate_marksman1", nome: "Magistrate (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Counterintelligence, FT Master (Jackals), Immunity (Shock), Specialist Operative", weapon: "Combi Rifle, Nanopulser", equip: "Biometric Visor, Heavy Pistol, Stun Pistol(+1B), CC Weapon" },
    { id: "magistrate_marksman2", nome: "Magistrate (MULTI Marksman Rifle)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Counterintelligence, FT Master (Jackals), Immunity (Shock), Specialist Operative", weapon: "MULTI Marksman Rifle, Nanopulser", equip: "Biometric Visor, Heavy Pistol, Stun Pistol(+1B), CC Weapon" },
    { id: "magistrate_cmd", nome: "Magistrate (Chain of Command)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Chain of Command, Counterintelligence, FT Master (Jackals), Immunity (Shock), Specialist Operative", weapon: "Combi Rifle, Nanopulser", equip: "Biometric Visor, Heavy Pistol, Stun Pistol(+1B), CC Weapon" },
    { id: "magistrate_lt", nome: "Magistrate (Lieutenant, Strategos L1)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Lieutenant, Strategos L1, Counterintelligence, FT Master (Jackals), Immunity (Shock), Specialist Operative", weapon: "MULTI Marksman Rifle, Nanopulser", equip: "Biometric Visor, Heavy Pistol, Stun Pistol(+1B), CC Weapon" },
    { id: "blink_sniper", nome: "Blink (MULTI Sniper Rifle)", tipo: "LI", mov: "4-4", cc: 15, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "MULTI Sniper Rifle", equip: "Assault Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "blink_shockmarksman", nome: "Blink (X Visor, Shock Marksman Rifle)", tipo: "LI", mov: "4-4", cc: 15, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "Shock Marksman Rifle, Shock Mine", equip: "X Visor, Assault Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "blink_hrl", nome: "Blink (X Visor, Heavy Rocket Launcher)", tipo: "LI", mov: "4-4", cc: 15, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Mimetism (-6), Stealth, Surprise Attack (-3)", weapon: "Heavy Rocket Launcher(PS=5), WildParrot", equip: "X Visor, Assault Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },

    // ===== GROUP 16: Drummer, Drumbot, Banshee =====
    { id: "drummer_marksman1", nome: "Drummer (Marksman Rifle)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "-", weapon: "Marksman Rifle", equip: "360 Visor, Pistol, CC Weapon" },
    { id: "drumbot1", nome: "Drumbot_1", tipo: "REM", mov: "6-4", cc: 13, bs: 13, ph: 9, wip: 11, arm: 1, bts: 3, str: 1, s: 2, skills: "Courage, Mimetism (-3), Peripheral (Synchronized)", weapon: "MULTI Heavy Machine Gun", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "drumbot2", nome: "Drumbot_2", tipo: "REM", mov: "6-4", cc: 13, bs: 13, ph: 9, wip: 11, arm: 1, bts: 3, str: 1, s: 2, skills: "Courage, Mimetism (-3), Peripheral (Synchronized)", weapon: "Hyper-Rapid Magnetic Cannon", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "drummer_fd", nome: "Drummer (Forward Deployment [+4\"])", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Forward Deployment (+4\")", weapon: "Marksman Rifle", equip: "360 Visor, Pistol, CC Weapon" },
    { id: "drumbot3", nome: "Drumbot_3 (Neurocinetics)", tipo: "REM", mov: "6-4", cc: 13, bs: 13, ph: 9, wip: 11, arm: 1, bts: 3, str: 1, s: 2, skills: "Neurocinetics, Courage, Mimetism (-3), Peripheral (Synchronized)", weapon: "Feuerbach(+1B)", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "drumbot4", nome: "Drumbot_4 (Forward Deployment [+4\"])", tipo: "REM", mov: "6-4", cc: 13, bs: 13, ph: 9, wip: 11, arm: 1, bts: 3, str: 1, s: 2, skills: "Forward Deployment (+4\"), Courage, Mimetism (-3), Peripheral (Synchronized)", weapon: "Mk12(+1B), Heavy Rocket Launcher", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "drummer_fo", nome: "Drummer (Forward Observer)", tipo: "LI", mov: "4-4", cc: 14, bs: 13, ph: 10, wip: 12, arm: 1, bts: 3, w: 1, s: 2, skills: "Forward Observer", weapon: "Marksman Rifle, Flash Pulse", equip: "360 Visor, Pistol, CC Weapon" },
    { id: "drumbot5", nome: "Drumbot_5 (Forward Observer)", tipo: "REM", mov: "6-4", cc: 13, bs: 13, ph: 9, wip: 11, arm: 1, bts: 3, str: 1, s: 2, skills: "Forward Observer, Courage, Mimetism (-3), Peripheral (Synchronized)", weapon: "Heavy Flamethrower, Flash Pulse", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "banshee", nome: "Banshee", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Combat Jump, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Light Shotgun, Pulzar(+1B), D-Charges", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "banshee_hacker", nome: "Banshee (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Combat Jump, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Submachine Gun, Pulzar(+1B), D-Charges", equip: "Multispectral Visor L1, Hacking Device, Pistol, CC Weapon" },

    // ===== GROUP 17: Banshee, Black A.I.R. FTO, Black A.I.R., Firefly =====
    { id: "banshee_wildparrot", nome: "Banshee (WildParrot)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Combat Jump, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Submachine Gun, Pulzar(+1B), D-Charges, WildParrot", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "banshee_khacker", nome: "Banshee (Hacker, Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Combat Jump, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Submachine Gun, Pulzar(+1B), D-Charges", equip: "Multispectral Visor L1, Killer Hacking Device, Pistol, CC Weapon" },
    { id: "blackair_fto_hacker", nome: "Black A.I.R. FTO (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Combat Instinct, Mimetism (-3), Number 2, Terrain (Total)", weapon: "Submachine Gun, Nanopulser, D-Charges", equip: "Multispectral Visor L2, Hacking Device, Pistol, CC Weapon" },
    { id: "blackair_fto_fo", nome: "Black A.I.R. FTO (Forward Observer)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Forward Observer, Combat Instinct, Mimetism (-3), Number 2, Terrain (Total)", weapon: "K1 Marksman Rifle, Nanopulser, Flash Pulse", equip: "Multispectral Visor L2, Pistol, CC Weapon" },
    { id: "blackair_fto_neuro", nome: "Black A.I.R. FTO (Neurocinetics)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Neurocinetics, Combat Instinct, Mimetism (-3), Number 2, Terrain (Total)", weapon: "MULTI Sniper Rifle, Nanopulser", equip: "Multispectral Visor L2, Pistol, CC Weapon" },
    { id: "blackair_khacker", nome: "Black A.I.R. (Hacker, Parachutist [Dep. Zone], Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Parachutist, Combat Instinct, Mimetism (-3), Number 2, Terrain (Total)", weapon: "Submachine Gun, Flash Pulse(+1B), D-Charges", equip: "Multispectral Visor L2, Killer Hacking Device, Pistol, CC Weapon" },
    { id: "firefly_hrl", nome: "Firefly (Heavy Rocket Launcher)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Heavy Rocket Launcher, D-Charges, AP Mine", equip: "Albedo (-6), Assault Pistol, CC Weapon" },
    { id: "firefly_cmd", nome: "Firefly (Chain of Command)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "Chain of Command, BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Submachine Gun, Panzerfaust, D-Charges, AP Mine", equip: "Albedo (-6), Pistol, CC Weapon" },
    { id: "firefly_engineer", nome: "Firefly (Engineer, Deactivator)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "Engineer, BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Submachine Gun, Panzerfaust, D-Charges, AP Mine", equip: "Albedo (-6), GizmoKit, Pistol, CC Weapon" },
    { id: "firefly_minelayer", nome: "Firefly (Minelayer)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "Minelayer, BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Submachine Gun, Panzerfaust, D-Charges, AP Mine, Armed Turret (Marksman Rifle)", equip: "Albedo (-6), Pistol, CC Weapon" },

    // ===== GROUP 18: Firefly, Griffin, Hetkari =====
    { id: "firefly_paramedic", nome: "Firefly (Paramedic)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "Paramedic, BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Combi Rifle, Panzerfaust, D-Charges, AP Mine", equip: "Albedo (-6), MediKit, Pistol, CC Weapon" },
    { id: "firefly_hacker", nome: "Firefly (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 17, bs: 13, ph: 11, wip: 13, arm: 2, bts: 6, w: 1, s: 2, skills: "Hacker, BS Attack (SR-1), Immunity (Shock), NCO, Stealth, Terrain (Total)", weapon: "Submachine Gun, Panzerfaust, D-Charges, AP Mine", equip: "Albedo (-6), Hacking Device, Pistol, CC Weapon" },
    { id: "griffin_multi", nome: "Griffin (MULTI Rifle)", tipo: "HI", mov: "6-2", cc: 16, bs: 14, ph: 12, wip: 12, arm: 4, bts: 6, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\"), Terrain (Desert)", weapon: "MULTI Rifle, Pulzar", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "griffin_hmg", nome: "Griffin (Heavy Machine Gun)", tipo: "HI", mov: "6-2", cc: 16, bs: 14, ph: 12, wip: 12, arm: 4, bts: 6, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\"), Terrain (Desert)", weapon: "Heavy Machine Gun, Pulzar", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "griffin_feuerbach", nome: "Griffin (Feuerbach)", tipo: "HI", mov: "6-2", cc: 16, bs: 14, ph: 12, wip: 12, arm: 4, bts: 6, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\"), Terrain (Desert)", weapon: "Feuerbach, Pulzar", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "griffin_lt", nome: "Griffin (Lieutenant)", tipo: "HI", mov: "6-2", cc: 16, bs: 14, ph: 12, wip: 12, arm: 4, bts: 6, w: 2, s: 2, skills: "Lieutenant, Courage, Immunity (Shock), Jump (3\"), Terrain (Desert)", weapon: "Heavy Machine Gun, Pulzar", equip: "Multispectral Visor L1, Pistol, CC Weapon" },
    { id: "hetkari_ml", nome: "Hetkari (Missile Launcher)", tipo: "HI", mov: "6-2", cc: 17, bs: 14, ph: 14, wip: 12, arm: 5, bts: 6, w: 2, s: 2, skills: "BS Attack (-3), Combat Instinct, Immunity (Shock), Marksmanship", weapon: "Missile Launcher, AP Submachine Gun", equip: "Breaker Pistol, CC Weapon(PS=6)" },
    { id: "hetkari_redfury", nome: "Hetkari (MULTI Red Fury)", tipo: "HI", mov: "6-2", cc: 17, bs: 14, ph: 14, wip: 12, arm: 5, bts: 6, w: 2, s: 2, skills: "BS Attack (-3), Combat Instinct, Immunity (Shock), Marksmanship", weapon: "MULTI Red Fury, E/Marat", equip: "Breaker Pistol, CC Weapon(PS=6)" },
    { id: "hetkari_lt1", nome: "Hetkari (Lieutenant, Missile Launcher)", tipo: "HI", mov: "6-2", cc: 17, bs: 14, ph: 14, wip: 12, arm: 5, bts: 6, w: 2, s: 2, skills: "Lieutenant, BS Attack (-3), Combat Instinct, Immunity (Shock), Marksmanship", weapon: "Missile Launcher, AP Submachine Gun", equip: "Breaker Pistol, CC Weapon(PS=6)" },
    { id: "hetkari_lt2", nome: "Hetkari (Lieutenant, MULTI Red Fury)", tipo: "HI", mov: "6-2", cc: 17, bs: 14, ph: 14, wip: 12, arm: 5, bts: 6, w: 2, s: 2, skills: "Lieutenant, BS Attack (-3), Combat Instinct, Immunity (Shock), Marksmanship", weapon: "MULTI Red Fury, E/Marat", equip: "Breaker Pistol, CC Weapon(PS=6)" },

    // ===== GROUP 19: Scarecrow, Dr. Harper, Crux Knight =====
    { id: "scarecrow_bsg", nome: "Scarecrow (Boarding Shotgun)", tipo: "SK", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Nanopulser, D-Charges", equip: "Deployable Repeater, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "scarecrow_hacker", nome: "Scarecrow (Hacker, Hacking Device)", tipo: "SK", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Submachine Gun, Nanopulser, D-Charges", equip: "Hacking Device, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "scarecrow_khacker", nome: "Scarecrow (Hacker, Killer Hacking Device)", tipo: "SK", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Submachine Gun, Nanopulser, D-Charges", equip: "Killer Hacking Device, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "scarecrow_minelayer", nome: "Scarecrow (Minelayer)", tipo: "SK", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Minelayer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Nanopulser, D-Charges, AP Mine(PS=6)", equip: "Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "scarecrow_fo", nome: "Scarecrow (Forward Observer)", tipo: "SK", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Forward Observer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Submachine Gun, Nanopulser, D-Charges, Flash Pulse", equip: "Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "drharper_fto", nome: "Dr. Harper FTO", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Booty, Dodge (+3), Immunity (Shock), No Cover, No Wound Incapacitation, Specialist Operative, Tactical Awareness", weapon: "Plasma Carbine, E/M Mine", equip: "Nanoscreen, X Visor, Viral Pistol(+1B), CC Weapon" },
    { id: "drharper_fd", nome: "Dr. Harper (Forward Deployment [+8\"])", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Forward Deployment (+8\"), Booty, Dodge (+3), Immunity (Shock), No Cover, No Wound Incapacitation, Specialist Operative, Tactical Awareness", weapon: "Plasma Carbine, E/M Mine", equip: "Nanoscreen, X Visor, Viral Pistol(+1B), CC Weapon" },
    { id: "cruxknight_ap", nome: "Crux Knight (Surprise Attack [-3], Forward Deployment [+8\"], Hidden Deployment)", tipo: "HI", mov: "6-2", cc: 22, bs: 14, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Surprise Attack (-3), Forward Deployment (+8\"), Hidden Deployment, Berserk, BS Attack (+1SD), Immunity (Shock), Martial Arts L2, Natural Born Warrior, Religious Troop, Specialist Operative, Stealth", weapon: "AP Submachine Gun, Flash Pulse, D-Charges, Crazykoala", equip: "Albedo (-6), Pistol, DA CC Weapon(PS=5)" },
    { id: "cruxknight_fd", nome: "Crux Knight (Forward Deployment [+8\"])", tipo: "HI", mov: "6-2", cc: 22, bs: 14, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Forward Deployment (+8\"), Berserk, BS Attack (+1SD), Immunity (Shock), Martial Arts L2, Natural Born Warrior, Religious Troop, Specialist Operative, Stealth", weapon: "MULTI Marksman Rifle(PS=5), D-Charges, Crazykoala", equip: "Albedo (-6), MULTI Pistol, DA CC Weapon(PS=5)" },

    // ===== GROUP 20: Crux Knight FTO, Redeye, Maximus Agent, Saito Togan, Yuan Yuan =====
    { id: "cruxknight_fto1", nome: "Crux Knight FTO (Drop Bears)", tipo: "HI", mov: "6-2", cc: 22, bs: 14, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Berserk, BS Attack (+1SD), Immunity (Shock), Martial Arts L2, Natural Born Warrior, Religious Troop, Specialist Operative, Stealth", weapon: "MULTI Marksman Rifle(PS=5), Drop Bears, D-Charges", equip: "Albedo (-6), MULTI Pistol, DA CC Weapon(PS=5)" },
    { id: "cruxknight_fto2", nome: "Crux Knight FTO (Strategic Deployment)", tipo: "HI", mov: "6-2", cc: 22, bs: 14, ph: 14, wip: 13, arm: 5, bts: 6, w: 2, s: 2, skills: "Strategic Deployment, Berserk, BS Attack (+1SD), Immunity (Shock), Martial Arts L2, Natural Born Warrior, Religious Troop, Specialist Operative, Stealth", weapon: "MULTI Marksman Rifle(PS=5), Drop Bears, D-Charges", equip: "Albedo (-6), MULTI Pistol, DA CC Weapon(PS=5)" },
    { id: "redeye", nome: "Redeye", tipo: "VH", mov: "8-2", cc: 0, bs: 13, ph: 13, wip: 13, arm: 6, bts: 6, str: 2, s: 7, skills: "Aerial, Courage, Dodge (-3), Gizmokit (PH=14), Mimetism (-6), No Cover, Remote Presence, Super-Jump (Jet Propulsion), Super-Jump (3\"), Terrain (Total)", weapon: "Spitfire, Chain Rifle, Blitzen", equip: "-" },
    { id: "maximusagent", nome: "Maximus Agent", tipo: "MI", mov: "6-2", cc: 23, bs: 12, ph: 13, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "CC Attack (-6), Courage, Dodge (+1\"), Immunity (ARM), Natural Born Warrior, No Wound Incapacitation, Specialist Operative, Tactical Awareness", weapon: "Thunderbolt(+2B), E/M Carbine", equip: "Heavy Pistol, AP+DA CC Weapon(PS=6)" },
    { id: "saitotogan", nome: "Saito Togan", tipo: "SK", mov: "4-4", cc: 24, bs: 11, ph: 13, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Camouflage, Courage, Dodge (+1\"), Hidden Deployment, Infiltration, Martial Arts L4, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "T2 Boarding Shotgun, Smoke Grenades", equip: "Bangbomb (+4), Pistol, EXP CC Weapon(PS=4)", deployState: "CAMO", state: "CAMO" },
    { id: "yuanyuan1", nome: "Yuan Yuan (Chain Rifle)", tipo: "WB", mov: "4-4", cc: 22, bs: 10, ph: 14, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Booty, Combat Jump (PH=11), Impetuous, No Cover, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Chain Rifle, Smoke Grenades", equip: "Heavy Pistol, AP CC Weapon(PS=6)" },

    // ===== GROUP 21: Yuan Yuan, Druze, Scarface Loadout Alpha, Turtlemek, Cordelia Turner =====
    { id: "yuanyuan2", nome: "Yuan Yuan (Boarding Shotgun)", tipo: "WB", mov: "4-4", cc: 22, bs: 10, ph: 14, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Booty, Combat Jump (PH=11), Impetuous, No Cover, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Boarding Shotgun, Smoke Grenades", equip: "Pistol, AP CC Weapon(PS=6)" },
    { id: "yuanyuan3", nome: "Yuan Yuan (Rifle)", tipo: "WB", mov: "4-4", cc: 22, bs: 10, ph: 14, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Booty, Combat Jump (PH=11), Impetuous, No Cover, Parachutist, Super-Jump (Jet Propulsion)", weapon: "Rifle, Smoke Grenades", equip: "Pistol, AP CC Weapon(PS=6)" },
    { id: "druze_combi", nome: "Druze (Combi Rifle)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Warhorse", weapon: "Combi Rifle, Chain-colt", equip: "X Visor, Viral Pistol, CC Weapon" },
    { id: "druze_hmg", nome: "Druze (Heavy Machine Gun)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Warhorse", weapon: "Heavy Machine Gun, Chain-colt", equip: "X Visor, Viral Pistol, CC Weapon" },
    { id: "druze_panzerfaust", nome: "Druze (Panzerfaust)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Warhorse", weapon: "Combi Rifle, Chain-colt, Panzerfaust", equip: "X Visor, Viral Pistol, CC Weapon" },
    { id: "druze_grenadelauncher", nome: "Druze (Grenade Launcher, E/M Grenade Launcher)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Warhorse", weapon: "Combi Rifle, Chain-colt, Grenade Launcher, E/M Grenade Launcher", equip: "X Visor, Viral Pistol, CC Weapon" },
    { id: "druze_shockmarksman", nome: "Druze (Shock Marksman Rifle)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "BS Attack (SR-1), Warhorse", weapon: "Shock Marksman Rifle, Chain-colt", equip: "X Visor, Viral Pistol, CC Weapon" },
    { id: "druze_hacker", nome: "Druze (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Hacker, BS Attack (SR-1), Warhorse", weapon: "Combi Rifle, Pitcher, D-Charges", equip: "X Visor, Hacking Device, Viral Pistol, CC Weapon" },
    { id: "druze_khacker", nome: "Druze (Hacker, Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Hacker, BS Attack (SR-1), Warhorse", weapon: "Combi Rifle, Pitcher, D-Charges", equip: "X Visor, Killer Hacking Device, Viral Pistol, CC Weapon" },
    { id: "scarfaceloadout_alpha", nome: "Scarface Loadout Alpha", tipo: "TAG", mov: "6-4", cc: 22, bs: 13, ph: 16, wip: 13, arm: 7, bts: 6, str: 3, s: 7, skills: "Berserk (+3), BS Attack (SR-1), CC Attack (-3), Courage, Dodge (PH=11), Gizmokit (PH=11), Tactical Awareness", weapon: "Mk12(+1B), Heavy Rocket Launcher(+1B)", equip: "ECM (Guided -6), ECM (Hacker -3), DA CC Weapon(PS=4)" },
    { id: "turtlemek", nome: "Turtlemek (REM)", tipo: "REM", mov: "6-4", cc: 0, bs: 0, ph: 10, wip: 12, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Dodge (+3), Mimetism (-3), Peripheral (Ancillary), Specialist Operative", weapon: "-", equip: "-" },
    { id: "cordeliaturner", nome: "Cordelia Turner", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Courage, Engineer, Mimetism (-3)", weapon: "Combi Rifle, D-Charges, PARA Mine", equip: "Deactivator, GizmoKit, Boarding Pistol, CC Weapon" },

    // ===== Mercenari disponibili a PanOceania (pagine seguenti allpano.pdf) =====
    { id: "spector_fto", nome: "Spector (Parachutist, Combat Jump)", tipo: "LI", mov: "6-2", cc: 22, bs: 12, ph: 13, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Courage, Martial Arts L2, Mimetism (-6), Natural Born Warrior, No Wound Incapacitation, Specialist Operative, Stealth, Super-Jump (Jet Propulsion)", weapon: "Boarding Shotgun(+1B), Drop Bears", equip: "Bangbomb (+4), Boarding Pistol(PS=6), E/M CC Weapon(PS=6)" },
    { id: "spector_fto_regular", nome: "Spector FTO (Regular)", tipo: "LI", mov: "6-2", cc: 22, bs: 12, ph: 13, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Courage, Martial Arts L2, Mimetism (-6), Natural Born Warrior, No Wound Incapacitation, Specialist Operative, Stealth, Super-Jump (Jet Propulsion)", weapon: "MULTI Rifle, Drop Bears", equip: "Bangbomb (+4), Boarding Pistol(PS=6), CC Weapon(PS=6)" },
    { id: "scarfaceloadout_gamma", nome: "Scarface Loadout Gamma", tipo: "TAG", mov: "6-4", cc: 22, bs: 13, ph: 16, wip: 13, arm: 7, bts: 6, str: 3, s: 7, skills: "Berserk (+3), BS Attack (SR-1), CC Attack (-3), Courage, Dodge (PH=11), Gizmokit (PH=11), Tactical Awareness", weapon: "AP Spitfire(+1B), Panzerfaust", equip: "ECM (Guided -6), ECM (Hacker -3), DA CC Weapon(PS=4)" },
    { id: "anaconda", nome: "Anaconda", tipo: "TAG", mov: "6-2", cc: 18, bs: 13, ph: 16, wip: 13, arm: 7, bts: 6, str: 3, s: 7, skills: "BS Attack (SR-1), Courage, Dodge (PH=11), Gizmokit (PH=11), Tactical Awareness, Transmutation (Escape System -2)", weapon: "Heavy Machine Gun, Light Shotgun(+1B), Panzerfaust", equip: "ECM (Guided -6), AP CC Weapon(PS=4)" },
    { id: "operator", nome: "Operator", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Courage, Specialist Operative, Tactical Awareness", weapon: "Spitfire", equip: "Boarding Pistol, CC Weapon" },
    { id: "uhahu", nome: "Uhahu (Hacker)", tipo: "LI", mov: "4-4", cc: 12, bs: 11, ph: 10, wip: 14, arm: 0, bts: 0, w: 1, s: 2, skills: "Hacker, Courage, Immunity (Shock), No Wound Incapacitation", weapon: "Pitcher, D-Charges", equip: "Hacking Device Plus (UPGRADE: Total Control SR-2), Assault Pistol, CC Weapon" },
    { id: "monstrucker_bsg", nome: "Monstrucker (Boarding Shotgun)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Climbing Plus, Engineer", weapon: "Boarding Shotgun, Adhesive Launcher Rifle, E/M Grenades", equip: "Deactivator, GizmoKit, Pistol, CC Weapon" },
    { id: "monstrucker_smg", nome: "Monstrucker (Chain Rifle)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Climbing Plus, Engineer", weapon: "Submachine Gun, Chain Rifle, Drop Bears", equip: "Deactivator, GizmoKit, Pistol, CC Weapon" },
    { id: "monstrucker_360", nome: "Monstrucker (360 Visor)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 12, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Climbing Plus, Engineer", weapon: "Rifle, Light Shotgun, Akrylat-Kanone, D-Charges", equip: "Deactivator, GizmoKit, Pistol, CC Weapon" },
    { id: "emily", nome: "Emily", tipo: "LI", mov: "4-4", cc: 17, bs: 13, ph: 10, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Courage, Dogged, Forward Observer, Mimetism (-3), Number 2", weapon: "Combi Rifle, Grenade Launcher, E/M Grenade Launcher, Nanopulser, Flash Pulse", equip: "X Visor, Assault Pistol, CC Weapon" },
    { id: "emily_cmd", nome: "Emily (Chain of Command)", tipo: "LI", mov: "4-4", cc: 17, bs: 13, ph: 10, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Chain of Command, Courage, Dogged, Forward Observer, Mimetism (-3), Number 2", weapon: "Combi Rifle, Grenade Launcher, E/M Grenade Launcher, Nanopulser, Flash Pulse", equip: "X Visor, Assault Pistol, CC Weapon" },
    { id: "armand", nome: "Armand (Multispectral Visor L1)", tipo: "MI", mov: "4-4", cc: 21, bs: 13, ph: 12, wip: 13, arm: 2, bts: 3, w: 2, s: 2, skills: "BS Attack (Shock), Forward Deployment (+4\"), Immunity (Shock), Mimetism (-6), Natural Born Warrior, Stealth, Transmutation (1)", weapon: "MULTI Sniper Rifle, Nanopulser", equip: "Breaker Pistol(+1B), Viral CC Weapon(PS=7)" },
    { id: "cateran", nome: "Cateran", tipo: "LI", mov: "4-4", cc: 22, bs: 12, ph: 13, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage (1 Use), Climbing Plus, Mimetism (-3), Stealth, Surprise Attack (-3)", weapon: "T2 Sniper Rifle", equip: "Pistol, AP CC Weapon(PS=7)", deployState: "CAMO", state: "CAMO" },
    { id: "csu_breaker", nome: "CSU (Breaker Rifle)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "MetaChemistry, Sixth Sense", weapon: "Breaker Rifle, Nanopulser(+1B)", equip: "MULTI Pistol, PARA CC Weapon(-6)" },
    { id: "csu_bsg", nome: "CSU (Boarding Shotgun)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "MetaChemistry, Sixth Sense", weapon: "Boarding Shotgun, Adhesive Launcher Rifle(+1B)", equip: "MULTI Pistol, PARA CC Weapon(-6)" },
    { id: "csu_specops", nome: "CSU (Specialist Operative)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 10, wip: 12, arm: 0, bts: 3, w: 1, s: 2, skills: "Specialist Operative, MetaChemistry, Sixth Sense", weapon: "Breaker Combi Rifle, Nanopulser(+1B)", equip: "MULTI Pistol, PARA CC Weapon(-6)" },
    { id: "bashibazouk_contender", nome: "Bashi Bazouk (Contender)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 12, arm: 2, bts: 0, w: 1, s: 2, skills: "Combat Jump (PH=11), Parachutist, Surprise Attack (-3), Terrain (Zero-G)", weapon: "Contender(+1B)", equip: "Holomask, Holoprojector, Boarding Pistol(+1B), CC Weapon" },
    { id: "bashibazouk_ap", nome: "Bashi Bazouk (BS Attack [AP])", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 12, arm: 2, bts: 0, w: 1, s: 2, skills: "Combat Jump (PH=11), Parachutist, Surprise Attack (-3), Terrain (Zero-G)", weapon: "T2 Boarding Shotgun", equip: "Holomask, Holoprojector, Boarding Pistol(+1B), CC Weapon" },
    { id: "bashibazouk_specops", nome: "Bashi Bazouk (Specialist Operative)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 12, arm: 2, bts: 0, w: 1, s: 2, skills: "Specialist Operative, Combat Jump (PH=11), Parachutist, Surprise Attack (-3), Terrain (Zero-G)", weapon: "Breaker Rifle", equip: "Holomask, Holoprojector, Boarding Pistol(+1B), CC Weapon" },
    { id: "carmen", nome: "Carmen", tipo: "WB", mov: "8-4", cc: 22, bs: 11, ph: 13, wip: 13, arm: 1, bts: 0, w: 1, s: 4, skills: "Booty, CC Attack (-6), Courage, Dodge (+2\"), Dogged, Impetuous, Limited Cover, Mimetism (-3), Natural Born Warrior", weapon: "Chain Rifle(+1B), Smoke Grenades, Smoke Grenade Launcher", equip: "Motorcycle, AP Heavy Pistol(+1B), DA CC Weapon(PS=6)" },
    { id: "batard", nome: "Bâtard", tipo: "WB", mov: "6-6", cc: 22, bs: 0, ph: 15, wip: 13, arm: 1, bts: 0, w: 1, s: 5, skills: "CC Attack (Shock), Courage, Dodge (+2\"), Dogged, Peripheral (Synchronized), Sensor", weapon: "-", equip: "Trench-Hammer, AP CC Weapon(PS=5)" },
    { id: "mirandaashcroft_bsg", nome: "Miranda Ashcroft (Boarding Shotgun)", tipo: "LI", mov: "4-4", cc: 19, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (-6), Marksmanship, Mimetism (-6), Specialist Operative, Stealth", weapon: "Boarding Shotgun, PARA Mine", equip: "Boarding Pistol, Monofilament CC Weapon" },
    { id: "mirandaashcroft_multi", nome: "Miranda Ashcroft (MULTI Rifle)", tipo: "LI", mov: "4-4", cc: 19, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (-6), Marksmanship, Mimetism (-6), Specialist Operative, Stealth", weapon: "MULTI Rifle, PARA Mine", equip: "Boarding Pistol, Monofilament CC Weapon" },
    { id: "mirandaashcroft_combi", nome: "Miranda Ashcroft (Combi Rifle, E/Mitter)", tipo: "LI", mov: "4-4", cc: 19, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (-6), Marksmanship, Mimetism (-6), Specialist Operative, Stealth", weapon: "Combi Rifle, E/Mitter(+1B), PARA Mine", equip: "Boarding Pistol, Monofilament CC Weapon" },
    { id: "wildbill", nome: "Wild Bill (BS Attack [Shock])", tipo: "LI", mov: "6-2", cc: 15, bs: 13, ph: 11, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "BS Attack (SR-1), Courage, Dodge (+3), Marksmanship, No Wound Incapacitation", weapon: "Rifle", equip: "MULTI Pistol(+1B), CC Weapon" },
    { id: "bountyhunter_sniper", nome: "Bounty Hunter (Sniper Rifle)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Booty (ReRoll), Stealth", weapon: "Sniper Rifle", equip: "Breaker Pistol(+1B), PARA CC Weapon(-6)" },
    { id: "bountyhunter_smg", nome: "Bounty Hunter (Akrylat-Kanone)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Booty (ReRoll), Stealth", weapon: "Submachine Gun, Akrylat-Kanone", equip: "Breaker Pistol, PARA CC Weapon(-6)" },
    { id: "krakotrenegade_chainrifle", nome: "Krakot Renegade (BS Attack [+1B], Chain Rifle)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Berserk (+3), Dodge (+2\"), Forward Deployment (+4\"), MetaChemistry (ReRoll), No Cover, Religious Troop, Super-Jump, Warhorse", weapon: "Chain Rifle, Chest Mine, Grenades", equip: "Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "krakotrenegade_smg", nome: "Krakot Renegade (Submachine Gun)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Berserk (+3), Dodge (+2\"), Forward Deployment (+4\"), MetaChemistry (ReRoll), No Cover, Religious Troop, Super-Jump, Warhorse", weapon: "Submachine Gun(+1B), Chest Mine", equip: "Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "krakotrenegade_bsg", nome: "Krakot Renegade (Boarding Shotgun)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Berserk (+3), Dodge (+2\"), Forward Deployment (+4\"), MetaChemistry (ReRoll), No Cover, Religious Troop, Super-Jump, Warhorse", weapon: "Boarding Shotgun, Chest Mine", equip: "Heavy Pistol, AP CC Weapon(PS=6)" },
    { id: "krakotrenegade_redfury", nome: "Krakot Renegade (Red Fury)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Berserk (+3), Dodge (+2\"), Forward Deployment (+4\"), MetaChemistry (ReRoll), No Cover, Religious Troop, Super-Jump, Warhorse", weapon: "Red Fury, Chest Mine", equip: "Heavy Pistol, AP CC Weapon(PS=6)" },
    { id: "majorlunah", nome: "Major Lunah", tipo: "LI", mov: "4-4", cc: 16, bs: 13, ph: 10, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "BS Attack (SR-1), Camouflage (1 Use), Immunity (Shock), Mimetism (-3), Religious Troop, Stealth, Surprise Attack (-3), Terrain (Total), Triangulated Fire", weapon: "Viral Sniper Rifle", equip: "Multispectral Visor L1, Boarding Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "cubejager", nome: "Cube Jäger (Paramedic)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Paramedic, Immunity (Shock), Parachutist, Stealth", weapon: "Boarding Shotgun", equip: "MediKit, Pistol, Monofilament CC Weapon" },
    { id: "oktavia", nome: "Oktavia", tipo: "LI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 2, bts: 0, w: 1, s: 2, skills: "BS Attack (+1B), Courage, Dogged, Sixth Sense", weapon: "Missile Launcher, Contender", equip: "Heavy Pistol, CC Weapon" },
    { id: "kunaininja", nome: "Kunai Ninja (BS Attack [AP])", tipo: "SK", mov: "4-4", cc: 21, bs: 12, ph: 12, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "Camouflage, Climbing Plus, Courage, Dodge (+1\"), Hidden Deployment, Martial Arts L3, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Shock Marksman Rifle", equip: "Pistol, Shock CC Weapon(PS=6)", deployState: "CAMO", state: "CAMO" },
    { id: "shonacarano", nome: "Shona Carano", tipo: "MI", mov: "6-2", cc: 23, bs: 11, ph: 14, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Courage, Dodge (+3), Dodge (+2\"), Frenzy, Immunity (Shock), Martial Arts L4, No Wound Incapacitation, Stealth, Super-Jump", weapon: "Submachine Gun, Nanopulser(+1B), Flash Pulse", equip: "Pistol" },
    { id: "hawkwood", nome: "Hawkwood", tipo: "MI", mov: "4-4", cc: 22, bs: 13, ph: 11, wip: 14, arm: 3, bts: 6, w: 1, s: 2, skills: "BS Attack (+1SD), Courage, Immunity (Shock), Martial Arts L1, Mimetism (-3), No Wound Incapacitation, Stealth, Terrain (Total)", weapon: "K1 Sniper Rifle, Nanopulser(+1B)", equip: "MULTI Pistol, DA CC Weapon(PS=7)" },
    { id: "hawkwood_cmd", nome: "Hawkwood (Chain of Command, X Visor)", tipo: "MI", mov: "4-4", cc: 22, bs: 13, ph: 11, wip: 14, arm: 3, bts: 6, w: 1, s: 2, skills: "Chain of Command, BS Attack (+1SD), Courage, Immunity (Shock), Martial Arts L1, Mimetism (-3), No Wound Incapacitation, Stealth, Terrain (Total)", weapon: "Combi Rifle(+1B), Nanopulser(+1B)", equip: "X Visor, MULTI Pistol, DA CC Weapon(PS=7)" },
    { id: "liangkai", nome: "Liang Kai", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 0, bts: 3, w: 1, s: 2, skills: "Berserk, Dodge (+1\"), Forward Deployment (+4\"), FT Master (Shaolin), Impetuous, Limited Cover, Martial Arts L4, Mimetism (-3), No Wound Incapacitation, Religious Troop, Stealth, Super-Jump", weapon: "Chain Rifle, Light Shotgun, Flash Pulse", equip: "Pistol, EXP CC Weapon(PS=4)" },
    { id: "fiddler_fto_sj", nome: "Fiddler FTO (Super-Jump)", tipo: "LI", mov: "6-4", cc: 18, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, str: 1, s: 2, skills: "Super-Jump, CC Attack (+1B), Dodge (+3), Dodge (+1\"), Engineer, Immunity (Critical), No Wound Incapacitation", weapon: "Contender(+1B), Drop Bears, D-Charges", equip: "GizmoKit, Breaker Pistol, PARA CC Weapon(-3)" },
    { id: "fiddler_climbing", nome: "Fiddler (Climbing Plus)", tipo: "LI", mov: "6-4", cc: 18, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, str: 1, s: 2, skills: "CC Attack (+1B), Climbing Plus, Dodge (+3), Dodge (+1\"), Engineer, Immunity (Critical), No Wound Incapacitation", weapon: "Contender(+1B), Drop Bears, D-Charges", equip: "GizmoKit, Breaker Pistol, PARA CC Weapon(-3)" },
    { id: "jackbot_x2", nome: "2x Jackbot (REM)", tipo: "REM", mov: "6-4", cc: 16, bs: 11, ph: 10, wip: 12, arm: 0, bts: 3, str: 1, s: 1, skills: "Climbing Plus, Courage, Explode, Peripheral (Synchronized)", weapon: "Vulkan Shotgun", equip: "-" },
    { id: "digger", nome: "Digger", tipo: "HI", mov: "4-4", cc: 21, bs: 11, ph: 13, wip: 12, arm: 3, bts: 0, w: 2, s: 2, skills: "Booty, CC Attack (+1B), Dodge (+1\"), Immunity (Shock), Impetuous, Natural Born Warrior, No Cover, Transmutation (1)", weapon: "Rifle, Light Shotgun, Grenades", equip: "Pistol, AP CC Weapon(PS=6)" },
    { id: "triphammer_spitfire", nome: "Triphammer (AP Spitfire, Heavy Flamethrower)", tipo: "TAG", mov: "6-4", cc: 17, bs: 13, ph: 16, wip: 12, arm: 7, bts: 3, str: 3, s: 7, skills: "Booty, BS Attack (SR-1), CC Attack (Antimaterial), Dodge (PH=9), Gizmokit (PH=10), Tactical Awareness, Transmutation (2)", weapon: "AP Spitfire, Heavy Flamethrower", equip: "AP CC Weapon(PS=4)" },
    { id: "triphammer_thunderbolt", nome: "Triphammer (Heavy Shotgun, Thunderbolt)", tipo: "TAG", mov: "6-4", cc: 17, bs: 13, ph: 16, wip: 12, arm: 7, bts: 3, str: 3, s: 7, skills: "Booty, BS Attack (SR-1), CC Attack (Antimaterial), Dodge (PH=9), Gizmokit (PH=10), Tactical Awareness, Transmutation (2)", weapon: "Heavy Shotgun, Thunderbolt(+1B)", equip: "AP CC Weapon(PS=4)" },
    { id: "triphammer_chaincolt", nome: "Triphammer (AP Spitfire, Chain-colt)", tipo: "TAG", mov: "6-4", cc: 17, bs: 13, ph: 16, wip: 12, arm: 7, bts: 3, str: 3, s: 7, skills: "Booty, BS Attack (SR-1), CC Attack (Antimaterial), Dodge (PH=9), Gizmokit (PH=10), Tactical Awareness, Transmutation (2)", weapon: "AP Spitfire, Chain-colt(+1B)", equip: "AP CC Weapon(PS=4)" },
    { id: "triphammer_hrl", nome: "Triphammer (Heavy Shotgun, Heavy Rocket Launcher)", tipo: "TAG", mov: "6-4", cc: 17, bs: 13, ph: 16, wip: 12, arm: 7, bts: 3, str: 3, s: 7, skills: "Booty, BS Attack (SR-1), CC Attack (Antimaterial), Dodge (PH=9), Gizmokit (PH=10), Tactical Awareness, Transmutation (2)", weapon: "Heavy Shotgun, Heavy Rocket Launcher, Panzerfaust(+1B)", equip: "AP CC Weapon(PS=4)" },
    { id: "beasthunter_fto", nome: "Beasthunter FTO", tipo: "SK", mov: "4-4", cc: 21, bs: 11, ph: 13, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Mimetism (-3), Religious Troop, Stealth, Super-Jump, Terrain (Total)", weapon: "Heavy Flamethrower, Panzerfaust, AP Mine", equip: "Pistol, DA CC Weapon(PS=5)" },
    { id: "beasthunters_1", nome: "Beasthunters (Surprise Attack [-3], Camouflage, Forward Deployment [+8\"], AP Mine)", tipo: "SK", mov: "4-4", cc: 21, bs: 11, ph: 13, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage, Forward Deployment (+8\"), Mimetism (-3), Religious Troop, Stealth, Super-Jump, Terrain (Total)", weapon: "Heavy Flamethrower, Panzerfaust, AP Mine", equip: "Pistol, DA CC Weapon(PS=5)", deployState: "CAMO", state: "CAMO" },
    { id: "beasthunters_2", nome: "Beasthunters (Surprise Attack [-3], Camouflage, Forward Deployment [+8\"], Tactical Bow)", tipo: "SK", mov: "4-4", cc: 21, bs: 11, ph: 13, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Surprise Attack (-3), Camouflage, Forward Deployment (+8\"), Mimetism (-3), Religious Troop, Stealth, Super-Jump, Terrain (Total)", weapon: "Heavy Flamethrower, Tactical Bow, AP Mine", equip: "Pistol, DA CC Weapon(PS=5)", deployState: "CAMO", state: "CAMO" },
    { id: "yojimbo", nome: "Yojimbo", tipo: "WB", mov: "6-2", cc: 24, bs: 12, ph: 14, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Immunity (Critical), Martial Arts L4, Minelayer, No Cover, No Wound Incapacitation, Stealth", weapon: "Contender(+1B), Nanopulser, Smoke Grenades, Crazykoala", equip: "Pistol, DA CC Weapon(PS=3)" },
    { id: "motorizedyojimbo", nome: "Motorized Yojimbo", tipo: "WB", mov: "8-6", cc: 24, bs: 12, ph: 14, wip: 13, arm: 1, bts: 3, w: 1, s: 4, skills: "Courage, Dodge (+2\"), Immunity (Critical), Limited Cover, Martial Arts L4, Mimetism (-3), Minelayer, No Wound Incapacitation", weapon: "Contender(+1B), Nanopulser, Smoke Grenades, Smoke Grenade Launcher, Crazykoala", equip: "Motorcycle, Pistol, DA CC Weapon(PS=3)" },
    { id: "sforza_fto", nome: "Sforza FTO", tipo: "MI", mov: "4-4", cc: 19, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Combat Instinct, Dogged, Immunity (ARM), Religious Troop, Stealth", weapon: "Viral Rifle, Adhesive Launcher Rifle(+1B), Nanopulser", equip: "Holomask, X Visor, Heavy Pistol(+1B), PARA CC Weapon(-9)" },
    { id: "valeryagromoz", nome: "Valerya Gromoz (Hacker)", tipo: "LI", mov: "4-4", cc: 15, bs: 11, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker", weapon: "Combi Rifle, Zapper, Pitcher", equip: "Hacking Device (UPGRADE: Total Control +1B), Pistol, CC Weapon" },
    { id: "aidaswanson", nome: "Aïda Swanson (Minelayer)", tipo: "LI", mov: "4-4", cc: 19, bs: 12, ph: 11, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Minelayer, Booty, Courage, Forward Deployment (+4\"), Martial Arts L2, Mimetism (-3), Shasvastii, Stealth", weapon: "Submachine Gun(+1B), Viral Mine", equip: "Viral Pistol, Shock CC Weapon" },
    { id: "liberto", nome: "Liberto", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 11, wip: 12, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage (1 Use), Courage, Dodge (+3), Dodge (+1\"), Dogged, Forward Deployment (+8\"), Frenzy, Terrain (Aquatic)", weapon: "Submachine Gun, Chain-colt", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "valkyrie", nome: "Valkyrie", tipo: "MI", mov: "4-4", cc: 22, bs: 12, ph: 13, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Berserk (+3), Courage, Dodge (+2\"), Frenzy, Immunity (Enhanced), Martial Arts L3, Natural Born Warrior, No Wound Incapacitation", weapon: "Heavy Shotgun, Grenades", equip: "Heavy Pistol, EXP CC Weapon(PS=5)" },
    { id: "kaplan_combi", nome: "Kaplan (Combi Rifle, D-Charges)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Combi Rifle, Adhesive Launcher Rifle, D-Charges", equip: "Boarding Pistol, CC Weapon" },
    { id: "kaplan_sniper", nome: "Kaplan (MULTI Sniper Rifle)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "MULTI Sniper Rifle", equip: "Boarding Pistol, CC Weapon" },
    { id: "kaplan_spitfire", nome: "Kaplan (Spitfire)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Spitfire", equip: "Boarding Pistol, CC Weapon" },
    { id: "kaplan_doctor", nome: "Kaplan (Doctor)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Doctor, Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Combi Rifle, Blitzen", equip: "MediKit, Boarding Pistol, CC Weapon" },
    { id: "kaplan_blitzen", nome: "Kaplan (Blitzen)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Combi Rifle, Blitzen", equip: "Boarding Pistol, CC Weapon" },
    { id: "kaplan_hrl", nome: "Kaplan (Heavy Rocket Launcher)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Heavy Rocket Launcher, Light Shotgun", equip: "Boarding Pistol, CC Weapon" },
    { id: "kaplan_engineer", nome: "Kaplan (Engineer, Deactivator)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Engineer, Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Combi Rifle, Adhesive Launcher Rifle, D-Charges", equip: "GizmoKit, Boarding Pistol, CC Weapon" },
    { id: "kaplan_specops", nome: "Kaplan (Specialist Operative)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Specialist Operative, Combat Instinct, Courage, Immunity (Shock), Mimetism (-3)", weapon: "Combi Rifle, Blitzen", equip: "Boarding Pistol, CC Weapon" },
    { id: "laxmee", nome: "Laxmee (Hacker)", tipo: "LI", mov: "4-4", cc: 18, bs: 11, ph: 10, wip: 14, arm: 2, bts: 6, w: 1, s: 2, skills: "Hacker, Mimetism (-3), Minelayer", weapon: "Submachine Gun, Pitcher, Cybermine, D-Charges", equip: "Hacking Device Plus (UPGRADE: Fairy Dust), Pistol, CC Weapon" },
    { id: "hannibal_cmd", nome: "Hannibal (Chain of Command)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 14, arm: 2, bts: 3, w: 1, s: 2, skills: "Chain of Command, Courage, Discover (+3), Dodge (+3), Immunity (Shock), No Wound Incapacitation", weapon: "Boarding Shotgun, Nanopulser", equip: "Biometric Visor, Pistol, CC Weapon" },
    { id: "hannibal_strategic", nome: "Hannibal (Chain of Command, Strategic Deployment)", tipo: "LI", mov: "4-4", cc: 16, bs: 12, ph: 11, wip: 14, arm: 2, bts: 3, w: 1, s: 2, skills: "Chain of Command, Strategic Deployment, Courage, Discover (+3), Dodge (+3), Immunity (Shock), No Wound Incapacitation", weapon: "Boarding Shotgun, Nanopulser", equip: "Biometric Visor, Pistol, CC Weapon" },
    { id: "samsa", nome: "Samsa", tipo: "MI", mov: "6-2", cc: 15, bs: 13, ph: 11, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Decoy (1), Dodge (+1\"), Exrah, Infiltration, Mimetism (-3), Specialist Operative, Super-Jump, Surprise Attack (-3)", weapon: "Plasma Rifle, D-Charges", equip: "Pistol, CC Weapon" }
];


// Dichiarazione di versione per il controllo incrociato fra chat.
// UN SOLO punto in cui il numero e` scritto: la riga @versione in testa al file.
// Qui non viene ripetuto, viene LETTO da li`, cosi` non possono divergere.
// Funziona anche se questo file si carica PRIMA del motore: in quel caso la
// versione resta in coda e il motore la raccoglie all'avvio.
(function () {
    var g = (typeof window !== 'undefined') ? window : globalThis;
    var FILE = 'database_panoceania.js';
    var vers = null;

    // Node / test: leggo l'intestazione dal sorgente stesso.
    try {
        if (typeof require === 'function' && typeof __filename === 'string') {
            var testa = require('fs').readFileSync(__filename, 'utf8').slice(0, 200);
            var m = testa.match(/@versione\s+(\S+)/);
            if (m) vers = m[1];
        }
    } catch (e) { /* ambiente senza fs: si passa al ramo browser */ }

    // Browser: l'intestazione non e` leggibile a runtime. Il motore la ricava
    // dal sorgente gia` caricato; se non ci riesce resta null e viene segnalata
    // come "da verificare" invece di essere data per buona.
    if (!vers && g.MotoreN5 && g.MotoreN5.versioneDaIntestazione)
        vers = g.MotoreN5.versioneDaIntestazione(FILE);

    var v = { file: FILE, versione: vers, proprieta: 'DATABASE' };
    if (g.MotoreN5 && g.MotoreN5.dichiaraVersione) g.MotoreN5.dichiaraVersione(v.file, v.versione, v.proprieta);
    else { g.__versioniN5 = g.__versioniN5 || []; g.__versioniN5.push(v); }
})();
