// @versione 2026-09-23.1 | database_nomad.js | proprieta`: chat DATABASE
// ==========================================
// --- database_nomad.js ---
// Database Unità Nomadi COMPLETO (da lista ufficiale "all nomad", N5.2)
// Nomi skill/equip allineati al catalogo_n5.js (nomi canonici).
// ==========================================

window.DB_NOMADI = [
    // ===== GROUP 1: Grenzer, Hellcat =====
    { id: "grenzer_ml", nome: "Grenzer (Missile Launcher)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Courage, Immunity (Shock), Warhorse", weapon: "Missile Launcher", equip: "Multispectral Visor L1, Pistol, Breaker Pistol, CC Weapon" },
    { id: "grenzer_redfury", nome: "Grenzer (Red Fury)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Courage, Immunity (Shock), Warhorse", weapon: "Red Fury", equip: "Multispectral Visor L1, Pistol, Breaker Pistol, CC Weapon" },
    { id: "grenzer_fo", nome: "Grenzer (Forward Observer, Sensor, NCO)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Courage, Immunity (Shock), Warhorse, Forward Observer, Sensor, NCO", weapon: "Combi Rifle, Light Flamethrower(+1B), Flash Pulse", equip: "Multispectral Visor L1, Pistol, Breaker Pistol, CC Weapon" },
    { id: "grenzer_discover", nome: "Grenzer (Discover +3, Biometric Visor)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Courage, Immunity (Shock), Warhorse", weapon: "Combi Rifle, Light Flamethrower(+1B)", equip: "Biometric Visor, Pistol, Breaker Pistol, CC Weapon" },
    { id: "grenzer_marksmanship", nome: "Grenzer (Marksmanship)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Courage, Immunity (Shock), Warhorse, Marksmanship", weapon: "MULTI Sniper Rifle", equip: "Multispectral Visor L1, Pistol, Breaker Pistol, CC Weapon" },
    { id: "grenzer_lt", nome: "Grenzer (Lieutenant, Discover +3)", tipo: "MI", mov: "4-4", cc: 13, bs: 13, ph: 11, wip: 13, arm: 3, bts: 6, w: 1, s: 2, skills: "Lieutenant, Courage, Immunity (Shock), Warhorse", weapon: "Combi Rifle, Light Flamethrower(+1B)", equip: "Biometric Visor, Pistol, Breaker Pistol, CC Weapon" },
    { id: "hellcat_bsg", nome: "Hellcat (Boarding Shotgun)", tipo: "MI", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Combat Jump (+3), Courage, Parachutist, Super-Jump, Terrain (Zero-G)", weapon: "Boarding Shotgun, Adhesive Launcher Rifle, D-Charges", equip: "Pistol, CC Weapon" },
    { id: "hellcat_spitfire", nome: "Hellcat (Spitfire)", tipo: "MI", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Combat Jump (+3), Courage, Parachutist, Super-Jump, Terrain (Zero-G)", weapon: "Spitfire", equip: "Pistol, CC Weapon" },
    { id: "hellcat_hacker", nome: "Hellcat (Hacker)", tipo: "MI", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Combat Jump (+3), Courage, Parachutist, Super-Jump, Terrain (Zero-G)", weapon: "Boarding Shotgun, D-Charges", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "hellcat_paramedic", nome: "Hellcat (Paramedic)", tipo: "MI", mov: "4-4", cc: 14, bs: 12, ph: 12, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Paramedic, Combat Jump (+3), Courage, Parachutist, Super-Jump, Terrain (Zero-G)", weapon: "Combi Rifle", equip: "MediKit, Deployable Repeater, Pistol, CC Weapon" },
    // ===== GROUP 2: Intruder, Zondnautica, Heckler, Puppet Masters =====
    { id: "intruder_hmg", nome: "Intruder (HMG)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 12, wip: 14, arm: 3, bts: 0, w: 1, s: 2, skills: "Camouflage, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Heavy Machine Gun, Grenades", equip: "Multispectral Visor L2, Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "intruder_hacker", nome: "Intruder (Hacker, Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 12, wip: 14, arm: 3, bts: 0, w: 1, s: 2, skills: "Hacker, Camouflage, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "AP Submachine Gun(+1B), Pulzar(+1B), Grenades", equip: "Killer Hacking Device, Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "intruder_xvisor", nome: "Intruder (X Visor)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 12, wip: 14, arm: 3, bts: 0, w: 1, s: 2, skills: "Camouflage, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "MULTI Sniper Rifle", equip: "Multispectral Visor L2, X Visor, Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zondnautica_a", nome: "Zondnautica-A", tipo: "MI", mov: "8-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 4, skills: "Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Spitfire, Chain Rifle, Smoke Grenade Launcher", equip: "AI Motorcycle, Pistol, CC Weapon" },
    { id: "zondnaut_a", nome: "Zondnaut-A", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Spitfire", equip: "Pistol, CC Weapon" },
    { id: "zondnautica_b", nome: "Zondnautica-B", tipo: "MI", mov: "8-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 4, skills: "Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Boarding Shotgun, Chain Rifle, Smoke Grenade Launcher", equip: "AI Motorcycle, Pistol, CC Weapon" },
    { id: "zondnaut_b", nome: "Zondnaut-B", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Boarding Shotgun", equip: "Pistol, CC Weapon" },
    { id: "zondmate", nome: "Zondmate (REM)", tipo: "REM", mov: "8-4", cc: 13, bs: 10, ph: 10, wip: 11, arm: 1, bts: 3, str: 1, s: 5, skills: "Courage, Mimetism (-3), Peripheral (Synchronized), Transmutation (Auto)", weapon: "Chain Rifle, Smoke Grenade Launcher", equip: "AI Motorcycle, PARA CC Weapon(-3)" },
    { id: "heckler_bsg", nome: "Heckler (Boarding Shotgun)", tipo: "SK", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Zero-G)", weapon: "Boarding Shotgun(+1B), E/Marat", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "heckler_hacker", nome: "Heckler (Hacker, Killer Hacking Device)", tipo: "SK", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Zero-G)", weapon: "Combi Rifle, Cybermine", equip: "Killer Hacking Device, Assault Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "heckler_redfury", nome: "Heckler (Red Fury)", tipo: "SK", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Forward Deployment (+4\"), Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Zero-G)", weapon: "Red Fury", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "puppetmasters", nome: "Puppet Masters", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Counterintelligence", weapon: "Submachine Gun, Shock Mine", equip: "Pistol, CC Weapon" },
    // ===== GROUP 3: Puppet Masters (var), Puppetbot, Zero =====
    { id: "puppetmasters_mine", nome: "Puppet Masters (Minelayer)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Counterintelligence, Minelayer", weapon: "Submachine Gun, Shock Mine", equip: "Pistol, CC Weapon" },
    { id: "puppetmasters_hacker", nome: "Puppet Masters (Hacker)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Counterintelligence", weapon: "Submachine Gun, Shock Mine", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "puppetbot_minelayer", nome: "Puppetbot (Minelayer)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 3, str: 2, s: 1, skills: "BS Attack (+1B), Courage, Dodge (+3), Peripheral (Control), Transmutation (Auto)", weapon: "Red Fury", equip: "PARA CC Weapon(-3)" },
    { id: "puppetbot_fo", nome: "Puppetbot (Forward Observer)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 3, str: 2, s: 1, skills: "BS Attack (+1B), Courage, Dodge (+3), Peripheral (Control), Transmutation (Auto)", weapon: "Boarding Shotgun, Flash Pulse", equip: "PARA CC Weapon(-3)" },
    { id: "puppetbot_shock", nome: "Puppetbot (BS Attack Shock)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 3, str: 2, s: 1, skills: "BS Attack (+1B), Courage, Dodge (+3), Peripheral (Control), Transmutation (Auto)", weapon: "AP Marksman Rifle", equip: "PARA CC Weapon(-3)" },
    { id: "zero_combi", nome: "Zero (Combi Rifle)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Shock Mine", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zero_bsg", nome: "Zero (Boarding Shotgun)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Shock Mine, PARA Mine", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zero_emmine", nome: "Zero (E/M Mine)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, E/M Mine", equip: "Deployable Repeater, Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zero_hacker", nome: "Zero (Hacker, Killer Hacking Device)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Hacker, Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Shock Mine", equip: "Killer Hacking Device, Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zero_sniper", nome: "Zero (MULTI Sniper Rifle)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "MULTI Sniper Rifle, Shock Mine", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "zero_fo", nome: "Zero (Forward Observer)", tipo: "SK", mov: "4-4", cc: 15, bs: 11, ph: 12, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Forward Observer, Camouflage, Infiltration, Mimetism (-3), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Shock Mine, Flash Pulse", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    // ===== GROUP 4: Alguacil, Mary Problems, Spektr =====
    { id: "alguacil_combi", nome: "Alguacil (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "alguacil_hmg", nome: "Alguacil (HMG)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "alguacil_ml", nome: "Alguacil (Missile Launcher)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "-", weapon: "Missile Launcher", equip: "Pistol, CC Weapon" },
    { id: "alguacil_hacker", nome: "Alguacil (Hacker)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker", weapon: "Combi Rifle", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "alguacil_fo", nome: "Alguacil (Forward Observer)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Forward Observer", weapon: "Combi Rifle, Flash Pulse", equip: "Deployable Repeater, Pistol, CC Weapon" },
    { id: "alguacil_paramedic", nome: "Alguacil (Paramedic)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Paramedic", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },
    { id: "alguacil_lt", nome: "Alguacil (Lieutenant)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Lieutenant", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "alguacil_specops", nome: "Alguacil (Specialist Operative)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Specialist Operative", weapon: "Combi Rifle", equip: "Commlink [+1], Pistol, CC Weapon" },
    { id: "maryproblems", nome: "Mary Problems (Hacker)", tipo: "LI", mov: "4-4", cc: 14, bs: 12, ph: 10, wip: 14, arm: 1, bts: 6, w: 1, s: 2, skills: "Hacker, Climbing Plus, Dodge (+3), Forward Deployment (+4\"), Mimetism (-6)", weapon: "Submachine Gun, Zapper, Pitcher", equip: "Hacking Device (UPGRADE Oblivion +1B), Killer Hacking Device (UPGRADE Trinity AP), Pistol, CC Weapon" },
    { id: "spektr_sniper", nome: "Spektr (MULTI Sniper Rifle)", tipo: "SK", mov: "4-4", cc: 13, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "MULTI Sniper Rifle, Shock Mine", equip: "Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    // ===== GROUP 5: Spektr (var), Morlock =====
    { id: "spektr_emmine", nome: "Spektr (E/M Mine)", tipo: "SK", mov: "4-4", cc: 13, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Submachine Gun, E/M Mine", equip: "Deployable Repeater, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "spektr_hacker", nome: "Spektr (Hacker)", tipo: "SK", mov: "4-4", cc: 13, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, D-Charges", equip: "Hacking Device, Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "spektr_fo", nome: "Spektr (Forward Observer)", tipo: "SK", mov: "4-4", cc: 13, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Forward Observer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Boarding Shotgun, Shock Mine, Flash Pulse", equip: "Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "spektr_minelayer", nome: "Spektr (Minelayer)", tipo: "SK", mov: "4-4", cc: 13, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Minelayer, Camouflage, Hidden Deployment, Infiltration, Mimetism (-6), Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, D-Charges, E/M Mine, Shock Mine", equip: "Silenced Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    { id: "morlock_assault", nome: "Morlock (Assault Pistol)", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Impetuous, Martial Arts L2, MetaChemistry, No Cover", weapon: "Chain Rifle, Smoke Grenades", equip: "Assault Pistol, AP CC Weapon(PS=6)" },
    { id: "morlock_kobra_da", nome: "Morlock (Kobra Pistol, DA CC)", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Impetuous, Martial Arts L2, MetaChemistry, No Cover", weapon: "Chain Rifle, Smoke Grenades", equip: "Kobra Pistol, DA CC Weapon(PS=6)" },
    { id: "morlock_kobra_em", nome: "Morlock (Kobra Pistol, E/M CC)", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Impetuous, Martial Arts L2, MetaChemistry, No Cover", weapon: "Chain Rifle, Smoke Grenades", equip: "Kobra Pistol, E/M CC Weapon(PS=6)" },
    { id: "morlock_bsg", nome: "Morlock (Boarding Shotgun)", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Impetuous, Martial Arts L2, MetaChemistry, No Cover", weapon: "Boarding Shotgun, Smoke Grenades", equip: "Kobra Pistol, DA CC Weapon(PS=6)" },
    { id: "morlock_combi", nome: "Morlock (Combi Rifle)", tipo: "WB", mov: "4-4", cc: 23, bs: 11, ph: 13, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Courage, Dodge (+1\"), Impetuous, Martial Arts L2, MetaChemistry, No Cover", weapon: "Combi Rifle, Smoke Grenade Launcher", equip: "Kobra Pistol, DA CC Weapon(PS=6)" },
    // ===== GROUP 6: Perseus, Daktari, Clockmaker, Mobile Brigada, Interventor =====
    { id: "perseus_multi", nome: "Perseus (MULTI Rifle)", tipo: "WB", mov: "4-4", cc: 23, bs: 13, ph: 13, wip: 13, arm: 2, bts: 0, w: 1, s: 2, skills: "BS Attack (+1B), Courage, Dodge (+1\"), Frenzy, Martial Arts L3, Mimetism (-6), No Wound Incapacitation, Stealth, Super-Jump", weapon: "MULTI Rifle, Nanopulser, Smoke Grenades", equip: "AP Heavy Pistol, DA CC Weapon(PS=5)" },
    { id: "perseus_breaker", nome: "Perseus (Breaker Combi Rifle)", tipo: "WB", mov: "4-4", cc: 23, bs: 13, ph: 13, wip: 13, arm: 2, bts: 0, w: 1, s: 2, skills: "BS Attack (+1B), Courage, Dodge (+1\"), Frenzy, Martial Arts L3, Mimetism (-6), No Wound Incapacitation, Stealth, Super-Jump", weapon: "Breaker Combi Rifle, Nanopulser, Smoke Grenades", equip: "AP Heavy Pistol, DA CC Weapon(PS=5)" },
    { id: "daktari", nome: "Daktari (Doctor)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Doctor", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },
    { id: "clockmaker", nome: "Clockmaker (Engineer)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer", weapon: "Combi Rifle, D-Charges", equip: "Deactivator, GizmoKit(+1B), Pistol, CC Weapon" },
    { id: "clockmaker_turret", nome: "Clockmaker (Armed Turret)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer", weapon: "Combi Rifle, D-Charges, Armed Turret (Combi Rifle)", equip: "Deactivator, GizmoKit(+1B), Pistol, CC Weapon" },
    { id: "clockmaker_cover", nome: "Clockmaker (Deployable Cover)", tipo: "LI", mov: "4-4", cc: 14, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer", weapon: "Combi Rifle, D-Charges, Deployable Cover", equip: "Deactivator, GizmoKit(+1B), Pistol, CC Weapon" },
    { id: "mobilebrigada_multi", nome: "Mobile Brigada (MULTI Rifle)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\")", weapon: "MULTI Rifle", equip: "TinBot: Firewall (-6), Boarding Pistol(+1B), CC Weapon" },
    { id: "mobilebrigada_hmg", nome: "Mobile Brigada (HMG)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\")", weapon: "Heavy Machine Gun", equip: "Boarding Pistol(+1B), CC Weapon" },
    { id: "mobilebrigada_ml", nome: "Mobile Brigada (Missile Launcher)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\")", weapon: "Missile Launcher", equip: "Boarding Pistol(+1B), CC Weapon" },
    { id: "mobilebrigada_bsg", nome: "Mobile Brigada (Boarding Shotgun)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Courage, Immunity (Shock), Jump (3\")", weapon: "Boarding Shotgun", equip: "Boarding Pistol(+1B), CC Weapon" },
    { id: "mobilebrigada_hacker", nome: "Mobile Brigada (Hacker)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Hacker, Courage, Immunity (Shock), Jump (3\")", weapon: "Combi Rifle, D-Charges", equip: "TinBot: Firewall (-6), Boarding Pistol(+1B), CC Weapon" },
    { id: "mobilebrigada_lt", nome: "Mobile Brigada (Lieutenant)", tipo: "HI", mov: "6-2", cc: 18, bs: 13, ph: 13, wip: 13, arm: 5, bts: 3, w: 2, s: 2, skills: "Lieutenant, Courage, Immunity (Shock), Jump (3\")", weapon: "MULTI Rifle", equip: "TinBot: Firewall (-6), Boarding Pistol(+1B), CC Weapon" },
    { id: "interventor_hacker", nome: "Interventor (Hacker Plus)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 15, arm: 1, bts: 9, w: 1, s: 2, skills: "Hacker", weapon: "Combi Rifle", equip: "Hacking Device Plus, Pistol, CC Weapon" },
    { id: "interventor_bsg", nome: "Interventor (Boarding Shotgun)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 15, arm: 1, bts: 9, w: 1, s: 2, skills: "Hacker", weapon: "Boarding Shotgun", equip: "Hacking Device Plus, FastPanda, Pistol, CC Weapon" },
    // ===== GROUP 7: Mobile Brigada (var), Interventor (var) =====
    { id: "interventor_hacker_fastpanda", nome: "Interventor (Hacker Plus, FastPanda)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 15, arm: 1, bts: 9, w: 1, s: 2, skills: "Hacker", weapon: "Combi Rifle", equip: "Hacking Device Plus, FastPanda, Pistol, CC Weapon" },
    // ===== GROUP 8: Stempler Zond, Reaktion Zond, Vertigo Zond, Meteor Zond, Transductor Zond =====
    { id: "stempler_zond", nome: "Stempler Zond", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Climbing Plus, Courage, Forward Observer, Remote Presence, Sensor, Triangulated Fire", weapon: "Combi Rifle, Flash Pulse", equip: "Deactivator, Repeater, PARA CC Weapon(-3)" },
    { id: "stempler_zond_ta", nome: "Stempler Zond (Tactical Awareness)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Tactical Awareness, Climbing Plus, Courage, Forward Observer, Remote Presence, Sensor, Triangulated Fire", weapon: "Combi Rifle, Flash Pulse", equip: "Deactivator, Repeater, PARA CC Weapon(-3)" },
    { id: "reaktion_zond", nome: "Reaktion Zond (HMG)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Climbing Plus, Courage, Remote Presence, Total Reaction", weapon: "Heavy Machine Gun", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "reaktion_zond_tb", nome: "Reaktion Zond (Thunderbolt)", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Climbing Plus, Courage, Remote Presence, Total Reaction", weapon: "Thunderbolt(+1B)", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "vertigo_zond", nome: "Vertigo Zond (Missile Launcher)", tipo: "REM", mov: "6-4", cc: 13, bs: 12, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "BS Attack, Courage, Remote Presence", weapon: "Missile Launcher", equip: "PARA CC Weapon(-3)" },
    { id: "meteor_zond", nome: "Meteor Zond", tipo: "REM", mov: "6-4", cc: 14, bs: 11, ph: 12, wip: 13, arm: 0, bts: 6, str: 1, s: 3, skills: "Combat Jump, Courage, Forward Observer, Parachutist, Remote Presence, Sensor, Super-Jump, Triangulated Fire", weapon: "Light Shotgun, E/M Carbine, Flash Pulse", equip: "ECM (Hacker -3), PARA CC Weapon(-6)" },
    { id: "meteor_zond_bsg", nome: "Meteor Zond (Boarding Shotgun)", tipo: "REM", mov: "6-4", cc: 14, bs: 11, ph: 12, wip: 13, arm: 0, bts: 6, str: 1, s: 3, skills: "Combat Jump, Courage, Forward Observer, Parachutist, Remote Presence, Sensor, Super-Jump, Triangulated Fire", weapon: "Boarding Shotgun, Flash Pulse", equip: "ECM (Hacker -3), PARA CC Weapon(-6)" },
    { id: "transductor_zond", nome: "Transductor Zond", tipo: "REM", mov: "6-6", cc: 13, bs: 8, ph: 11, wip: 13, arm: 0, bts: 3, str: 1, s: 3, skills: "Courage, Mimetism (-3), Remote Presence", weapon: "Flash Pulse", equip: "Repeater, PARA CC Weapon(-3)" },
    // ===== GROUP 9: Zoe & Pi-Well, Moderator =====
    { id: "zoe_hacker", nome: "Zoe (Hacker)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Engineer, Immunity (Shock), Immunity (BTS)", weapon: "Combi Rifle, D-Charges", equip: "Deactivator, GizmoKit(+1B), Hacking Device (UPGRADE Zero Pain), Pistol, PARA CC Weapon(-3)" },
    { id: "piwell_sync", nome: "Pi-Well SYNC", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "BS Attack (+1B), Courage, Mimetism (-6), Peripheral (Synchronized)", weapon: "E/Marat, Pitcher, Jammer", equip: "Pistol, PARA CC Weapon(-6)" },
    { id: "piwell_fto", nome: "Pi-Well FTO", tipo: "REM", mov: "6-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Forward Observer, Mimetism (-6), Remote Presence, Sensor, Triangulated Fire", weapon: "Combi Rifle, Flash Pulse(+1B), Pitcher", equip: "ECM (Hacker -3), Repeater, PARA CC Weapon(-6)" },
    { id: "moderator_combi", nome: "Moderator (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Immunity (Shock)", weapon: "Combi Rifle", equip: "Pistol, PARA CC Weapon(-6)" },
    // ===== GROUP 10: Moderator (var), Sin-Eater, Szalamandra, Moran =====
    { id: "moderator_hacker", nome: "Moderator (Hacker)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Hacker, Immunity (Shock)", weapon: "Combi Rifle", equip: "Hacking Device, Pistol, PARA CC Weapon(-6)" },
    { id: "moderator_paramedic", nome: "Moderator (Paramedic)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Paramedic, Immunity (Shock)", weapon: "Combi Rifle", equip: "MediKit, Pistol, PARA CC Weapon(-6)" },
    { id: "moderator_lt", nome: "Moderator (Lieutenant)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Lieutenant, Immunity (Shock)", weapon: "Combi Rifle", equip: "Pistol, PARA CC Weapon(-6)" },
    { id: "moderator_specops", nome: "Moderator (Specialist Operative)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Specialist Operative, Immunity (Shock)", weapon: "Combi Rifle", equip: "Commlink [+1], Pistol, PARA CC Weapon(-6)" },
    { id: "moderator_emcarbine", nome: "Moderator (E/M Carbine)", tipo: "LI", mov: "4-4", cc: 18, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, w: 1, s: 2, skills: "Immunity (Shock)", weapon: "Boarding Shotgun, E/M Carbine", equip: "Pistol, PARA CC Weapon(-6)" },
    { id: "sineater_sniper", nome: "Sin-Eater (MULTI Sniper Rifle)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Immunity (Shock), Mimetism (-3), Neurocinetics, Religious Troop", weapon: "MULTI Sniper Rifle", equip: "Pistol, CC Weapon" },
    { id: "sineater_hmg", nome: "Sin-Eater (HMG)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Immunity (Shock), Mimetism (-3), Neurocinetics, Religious Troop", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "sineater_mk12", nome: "Sin-Eater (Mk12)", tipo: "MI", mov: "4-4", cc: 14, bs: 13, ph: 11, wip: 13, arm: 3, bts: 0, w: 1, s: 2, skills: "Immunity (Shock), Mimetism (-3), Neurocinetics, Religious Troop", weapon: "Mk12", equip: "Pistol, CC Weapon" },
    { id: "szalamandra", nome: "Szalamandra (TAG)", tipo: "TAG", mov: "6-4", cc: 17, bs: 14, ph: 16, wip: 13, arm: 8, bts: 9, str: 3, s: 7, skills: "BS Attack (SR-1), Dodge (PH=11), Gizmokit (PH=11), NCO", weapon: "Hyper-Rapid Magnetic Cannon, Heavy Flamethrower", equip: "ECM (Guided -6), CC Weapon(PS=5)" },
    { id: "szalamandra_robbybot", nome: "Robbybot (Szalamandra)", tipo: "REM", mov: "6-4", cc: 13, bs: 0, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Dodge (+3), Mimetism (-3), Peripheral (Ancillary), Specialist Operative", weapon: "-", equip: "-" },
    { id: "moran_camo", nome: "Moran (Surprise Attack, Camouflage)", tipo: "SK", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Courage, Forward Observer, Infiltration, Mimetism (-3), Minelayer, Stealth, Surprise Attack (-3), Terrain (Total)", weapon: "Combi Rifle, Flash Pulse, D-Charges, Crazykoala", equip: "Pistol, CC Weapon", deployState: "CAMO", state: "CAMO" },
    // ===== GROUP 11: Moran (var), Chimera, 3X Pupnik, Tsyklon, Lunokhod, Zondbot, Salyut =====
    { id: "moran_repeater", nome: "Moran (Repeater)", tipo: "SK", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Courage, Forward Observer, Infiltration, Mimetism (-3), Minelayer, Stealth, Terrain (Total)", weapon: "Combi Rifle, Flash Pulse, D-Charges, Crazykoala", equip: "Pistol, CC Weapon" },
    { id: "chimera", nome: "Chimera", tipo: "WB", mov: "6-4", cc: 24, bs: 11, ph: 13, wip: 12, arm: 1, bts: 0, w: 1, s: 2, skills: "CC Attack (-3), Climbing Plus, Dodge (+1\"), Immunity (Enhanced), Impetuous, Natural Born Warrior, No Cover", weapon: "Combi Rifle, Nanopulser, Eclipse Grenades", equip: "Pistol, Viral CC Weapon(PS=6)" },
    { id: "pupnik", nome: "3X Pupnik", tipo: "WB", mov: "6-4", cc: 19, bs: 4, ph: 13, wip: 10, arm: 0, bts: 0, w: 1, s: 2, skills: "Climbing Plus, Courage, Dodge (+1\"), Dodge (+6), Immunity (Enhanced), No Cover, Peripheral (Synchronized)", weapon: "-", equip: "DA CC Weapon(PS=7)" },
    { id: "tsyklon_spitfire", nome: "Tsyklon (Spitfire)", tipo: "REM", mov: "6-4", cc: 12, bs: 10, ph: 13, wip: 12, arm: 3, bts: 6, str: 1, s: 4, skills: "Climbing Plus, Courage, Remote Presence", weapon: "Spitfire, Chain Rifle, Pitcher", equip: "360 Visor, Repeater, X Visor, PARA CC Weapon(-6)" },
    { id: "tsyklon_feuerbach", nome: "Tsyklon (Feuerbach)", tipo: "REM", mov: "6-4", cc: 12, bs: 10, ph: 13, wip: 12, arm: 3, bts: 6, str: 1, s: 4, skills: "Climbing Plus, Courage, Remote Presence", weapon: "Feuerbach, Chain Rifle, Pitcher", equip: "360 Visor, Repeater, X Visor, PARA CC Weapon(-6)" },
    { id: "lunokhod", nome: "Lunokhod", tipo: "REM", mov: "8-2", cc: 14, bs: 12, ph: 10, wip: 13, arm: 3, bts: 6, str: 1, s: 4, skills: "Climbing Plus, Courage, Forward Deployment (+4\"), Minelayer, Remote Presence", weapon: "Heavy Shotgun, Heavy Flamethrower, E/Mitter, Crazykoala", equip: "PARA CC Weapon(-3)" },
    { id: "lunokhod_tb", nome: "Lunokhod (Thunderbolt)", tipo: "REM", mov: "8-2", cc: 14, bs: 12, ph: 10, wip: 13, arm: 3, bts: 6, str: 1, s: 4, skills: "Climbing Plus, Courage, Forward Deployment (+4\"), Minelayer, Remote Presence", weapon: "Heavy Shotgun, Thunderbolt, E/Mitter, Crazykoala", equip: "PARA CC Weapon(-3)" },
    { id: "zondbot", nome: "Zondbot", tipo: "REM", mov: "6-4", cc: 11, bs: 8, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Mimetism (-3), Peripheral (Servant)", weapon: "-", equip: "PARA CC Weapon(-3)" },
    { id: "salyut_evo", nome: "Salyut (EVO Hacking Device)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Courage, Remote Presence", weapon: "-", equip: "EVO Hacking Device, Baggage, PARA CC Weapon(-3)" },
    { id: "salyut_deactivator", nome: "Salyut (Deactivator, Repeater)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Courage, Remote Presence", weapon: "-", equip: "Deactivator, Repeater, Baggage, PARA CC Weapon(-3)" },
    // ===== GROUP 12: Salyut TR, Gecko, Securitate =====
    { id: "salyut_tr", nome: "Salyut (Total Reaction, Repeater)", tipo: "REM", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 2, bts: 3, str: 1, s: 4, skills: "Courage, Remote Presence", weapon: "Combi Rifle", equip: "Baggage, PARA CC Weapon(-3)" },
    { id: "gecko_multimarksman", nome: "Gecko (MULTI Marksman Rifle)", tipo: "TAG", mov: "6-2", cc: 15, bs: 13, ph: 14, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "BS Attack (+1B), BS Attack (SR-2), Dodge (PH=11), Gizmokit (PH=11), Tactical Awareness, Terrain (Zero-G)", weapon: "MULTI Marksman Rifle, Chain Rifle, Panzerfaust", equip: "ECM (Guided -6), CC Weapon(PS=6)" },
    { id: "gecko_mk12", nome: "Gecko (Mk12)", tipo: "TAG", mov: "6-2", cc: 15, bs: 13, ph: 14, wip: 13, arm: 6, bts: 6, str: 3, s: 6, skills: "BS Attack (+1B), BS Attack (SR-2), Dodge (PH=11), Gizmokit (PH=11), Tactical Awareness, Terrain (Zero-G)", weapon: "Mk12, Chain Rifle, Blitzen", equip: "ECM (Guided -6), CC Weapon(PS=6)" },
    { id: "gecko_robbybot", nome: "Robbybot (Gecko)", tipo: "REM", mov: "6-4", cc: 13, bs: 0, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Dodge (+3), Mimetism (-3), Peripheral (Ancillary), Specialist Operative, Terrain (Zero-G)", weapon: "-", equip: "-" },
    { id: "securitate_combi", nome: "Securitate (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Warhorse", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "securitate_hmg", nome: "Securitate (HMG)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Warhorse", weapon: "Heavy Machine Gun", equip: "Pistol, CC Weapon" },
    { id: "securitate_feuerbach", nome: "Securitate (Feuerbach)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Warhorse", weapon: "Feuerbach", equip: "Pistol, CC Weapon" },
    { id: "securitate_hacker", nome: "Securitate (Hacker)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker, Warhorse", weapon: "Combi Rifle", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "securitate_bsg", nome: "Securitate (Boarding Shotgun)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Warhorse", weapon: "Boarding Shotgun", equip: "Pistol, CC Weapon" },
    { id: "securitate_paramedic", nome: "Securitate (Paramedic)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Paramedic, Warhorse", weapon: "Combi Rifle", equip: "MediKit, Pistol, CC Weapon" },
    { id: "securitate_lt", nome: "Securitate (Lieutenant)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Lieutenant, Warhorse", weapon: "Combi Rifle", equip: "Pistol, CC Weapon" },
    { id: "securitate_specops", nome: "Securitate (Specialist Operative)", tipo: "LI", mov: "4-4", cc: 13, bs: 12, ph: 10, wip: 14, arm: 1, bts: 0, w: 1, s: 2, skills: "Specialist Operative, Warhorse", weapon: "Combi Rifle", equip: "Commlink [+1], Pistol, CC Weapon" },
    // ===== GROUP 13: Securitate (specops), Taskmaster, Warcor, Kriza Borac =====
    { id: "taskmaster_hmg", nome: "Taskmaster (HMG)", tipo: "HI", mov: "4-4", cc: 22, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Courage, Dodge (+1\"), FT Master, Immunity (Shock), Martial Arts L1, Minelayer, Stealth", weapon: "Heavy Machine Gun, Shock Mine", equip: "Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "taskmaster_redfury", nome: "Taskmaster (Red Fury)", tipo: "HI", mov: "4-4", cc: 22, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Courage, Dodge (+1\"), FT Master, Immunity (Shock), Martial Arts L1, Minelayer, Stealth", weapon: "Red Fury, Crazykoala", equip: "TinBot: Firewall (-3), Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "taskmaster_hrl", nome: "Taskmaster (Heavy Rocket Launcher)", tipo: "HI", mov: "4-4", cc: 22, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Courage, Dodge (+1\"), FT Master, Immunity (Shock), Martial Arts L1, Minelayer, Stealth", weapon: "Heavy Rocket Launcher, Light Shotgun, Crazykoala", equip: "Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "taskmaster_sd", nome: "Taskmaster (Strategic Deployment)", tipo: "HI", mov: "4-4", cc: 22, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Strategic Deployment, Courage, Dodge (+1\"), FT Master, Immunity (Shock), Martial Arts L1, Minelayer, Stealth", weapon: "Red Fury, Crazykoala", equip: "TinBot: Firewall (-3), Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "taskmaster_lt", nome: "Taskmaster (Lieutenant)", tipo: "HI", mov: "4-4", cc: 22, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Lieutenant, Courage, Dodge (+1\"), FT Master, Immunity (Shock), Martial Arts L1, Minelayer, Stealth", weapon: "Red Fury, Crazykoala", equip: "TinBot: Firewall (-3), Heavy Pistol, DA CC Weapon(PS=6)" },
    { id: "warcor", nome: "Warcor (360 Visor)", tipo: "LI", mov: "4-4", cc: 11, bs: 9, ph: 11, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Journalist L1", weapon: "Flash Pulse, Stun Pistol", equip: "360 Visor, PARA CC Weapon(-3)" },
    { id: "warcor_sixthsense", nome: "Warcor (Sixth Sense)", tipo: "LI", mov: "4-4", cc: 11, bs: 9, ph: 11, wip: 13, arm: 0, bts: 0, w: 1, s: 2, skills: "Sixth Sense, Journalist L1", weapon: "Flash Pulse, Stun Pistol", equip: "PARA CC Weapon(-3)" },
    { id: "krizaborac_mk12", nome: "Kriza Borac (Mk12)", tipo: "HI", mov: "4-4", cc: 19, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "BS Attack (+1B), BS Attack (-3), Courage, Immunity (Shock), Terrain (Total)", weapon: "Mk12, Submachine Gun", equip: "Heavy Pistol, CC Weapon" },
    { id: "krizaborac_lt", nome: "Kriza Borac (Lieutenant)", tipo: "HI", mov: "4-4", cc: 19, bs: 13, ph: 13, wip: 13, arm: 5, bts: 6, w: 2, s: 5, skills: "Lieutenant, BS Attack (+1B), BS Attack (-3), Courage, Immunity (Shock), Terrain (Total)", weapon: "Heavy Machine Gun", equip: "Heavy Pistol, CC Weapon" },
    // ===== GROUP 14: Kriza Borac, Evader =====
    { id: "evader_multi", nome: "Evader (MULTI Rifle)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "MULTI Rifle, Panzerfaust, D-Charges", equip: "Deactivator, Pistol, CC Weapon" },
    { id: "evader_spitfire", nome: "Evader (AP Spitfire)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "AP Spitfire, D-Charges", equip: "Deactivator, Pistol, CC Weapon" },
    { id: "evader_multi_tb", nome: "Evader (MULTI Rifle, TinBot)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "MULTI Rifle, Panzerfaust, D-Charges", equip: "TinBot: Firewall (-3), Deactivator, Pistol, CC Weapon" },
    { id: "evader_bsg", nome: "Evader (Boarding Shotgun)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "Boarding Shotgun, D-Charges, AP Mine", equip: "TinBot: Firewall (-3), Deactivator, Pistol, CC Weapon" },
    { id: "evader_feuerbach", nome: "Evader (Feuerbach)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "Feuerbach, D-Charges", equip: "TinBot: Firewall (-3), Deactivator, Pistol, CC Weapon" },
    { id: "evader_multi_gizmo", nome: "Evader (Engineer, GizmoKit)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Engineer, Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "Boarding Shotgun, D-Charges, AP Mine", equip: "GizmoKit, Deactivator, Pistol, CC Weapon" },
    { id: "evader_engineer", nome: "Evader (Engineer)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Engineer, Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "MULTI Rifle, Panzerfaust, D-Charges", equip: "GizmoKit, TinBot: Firewall (-3), Deactivator, Pistol, CC Weapon" },
    { id: "evader_spitfire_gizmo", nome: "Evader (AP Spitfire, Engineer)", tipo: "HI", mov: "4-4", cc: 15, bs: 13, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 2, skills: "Engineer, Climbing Plus, Courage, Immunity (Shock), No Wound Incapacitation, Specialist Operative, Terrain (Zero-G)", weapon: "AP Spitfire, D-Charges", equip: "GizmoKit, TinBot: Firewall (-3), Deactivator, Pistol, CC Weapon" },
    // ===== GROUP 15: Vostok, Jazz, Billie, Wolfgang Amadeus, Fiddler, Jackbot, Gator =====
    { id: "vostok", nome: "Vostok (Repeater)", tipo: "REM", mov: "6-4", cc: 14, bs: 12, ph: 10, wip: 13, arm: 3, bts: 6, str: 2, s: 4, skills: "Climbing Plus, Courage, Immunity (AP), Mimetism (-6), Remote Presence", weapon: "Mk12(PS=4)", equip: "PARA CC Weapon(-3)" },
    { id: "vostok_fto", nome: "Vostok FTO", tipo: "REM", mov: "6-4", cc: 14, bs: 12, ph: 10, wip: 13, arm: 3, bts: 6, str: 2, s: 4, skills: "Climbing Plus, Courage, Immunity (AP), Mimetism (-6), Remote Presence", weapon: "Mk12", equip: "PARA CC Weapon(-3)" },
    { id: "jazz", nome: "Jazz (Hacker)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 14, arm: 0, bts: 6, w: 1, s: 2, skills: "Hacker, -", weapon: "Submachine Gun, Pitcher, Cybermine", equip: "Hacking Device Plus (UPGRADE Trinity SR-1), Boarding Pistol, PARA CC Weapon(-3)" },
    { id: "jazz_fto", nome: "Jazz FTO (Hacker, Number 2)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 14, arm: 0, bts: 6, w: 1, s: 2, skills: "Hacker, Number 2", weapon: "Combi Rifle, Pitcher, Cybermine", equip: "Hacking Device Plus (UPGRADE Trinity SR-1), Boarding Pistol, PARA CC Weapon(-3)" },
    { id: "billie", nome: "Billie", tipo: "REM", mov: "6-4", cc: 13, bs: 10, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Remote Presence", weapon: "Flash Pulse, E/M Mine, Heavy Pistol", equip: "Repeater, PARA CC Weapon(-3)" },
    { id: "wolfgang", nome: "Wolfgang Amadeus", tipo: "WB", mov: "6-2", cc: 22, bs: 14, ph: 13, wip: 13, arm: 2, bts: 0, w: 1, s: 2, skills: "Berserk (+3), BS Attack (Continuous Damage), Climbing Plus, Courage, Dodge (+2\"), Dodge (+3), Frenzy, Immunity (ARM), Martial Arts L3, Terrain (Zero-G)", weapon: "MULTI Rifle(+1B), Chain-colt, Heavy Pistol", equip: "PARA CC Weapon(-6), DA CC Weapon(PS=4)" },
    { id: "fiddler", nome: "Fiddler (Climbing Plus)", tipo: "LI", mov: "6-4", cc: 18, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (+1B), Dodge (+3), Dodge (+1\"), Engineer, Immunity (Critical), No Wound Incapacitation", weapon: "Contender(+1B), Drop Bears, D-Charges", equip: "GizmoKit, Breaker Pistol, PARA CC Weapon(-3)" },
    { id: "fiddler_sj", nome: "Fiddler FTO (Super-Jump)", tipo: "LI", mov: "6-4", cc: 18, bs: 12, ph: 12, wip: 14, arm: 1, bts: 3, w: 1, s: 2, skills: "Super-Jump, CC Attack (+1B), Dodge (+3), Dodge (+1\"), Engineer, Immunity (Critical), No Wound Incapacitation", weapon: "Contender(+1B), Drop Bears, D-Charges", equip: "GizmoKit, Breaker Pistol, PARA CC Weapon(-3)" },
    { id: "jackbot", nome: "Jackbot", tipo: "REM", mov: "6-4", cc: 16, bs: 11, ph: 10, wip: 12, arm: 0, bts: 3, str: 1, s: 1, skills: "Climbing Plus, Courage, Explode, Peripheral (Synchronized)", weapon: "Vulkan Shotgun", equip: "-" },
    { id: "gator", nome: "Gator (TAG)", tipo: "TAG", mov: "6-4", cc: 20, bs: 14, ph: 15, wip: 13, arm: 8, bts: 6, str: 3, s: 7, skills: "BS Attack (SR-1), CC Attack (-3), Dodge (PH=11), Dodge (+2\"), Gizmokit (PH=11), NCO, Tactical Awareness", weapon: "MULTI Heavy Machine Gun, Chain Rifle(+1B), Mine Dispenser (Cybermines)", equip: "ECM (Guided -6), ECM (Hacker -3), E/M CC Weapon(PS=5)" },
    { id: "gator_robbybot", nome: "Robbybot (Gator)", tipo: "REM", mov: "6-4", cc: 13, bs: 0, ph: 10, wip: 13, arm: 0, bts: 3, str: 1, s: 1, skills: "Courage, Dodge (+3), Mimetism (-3), Peripheral (Ancillary), Specialist Operative", weapon: "-", equip: "-" },
    // ===== GROUP 16: Marspider, Kulak, Rounder =====
    { id: "marspider_ht", nome: "Marspider (Heavy Flamethrower)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (+1B), Climbing Plus, Courage, Dodge (+1\"), Martial Arts L1, Stealth, Terrain (Zero-G)", weapon: "Heavy Flamethrower(+1B), Flash Pulse, Panzerfaust", equip: "360 Visor, GizmoKit, Assault Pistol, DA CC Weapon(PS=7)" },
    { id: "marspider_grenades", nome: "Marspider (Grenades)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "CC Attack (+1B), Climbing Plus, Courage, Dodge (+1\"), Martial Arts L1, Stealth, Terrain (Zero-G)", weapon: "Heavy Flamethrower(+1B), Flash Pulse, Grenades(+1B)", equip: "360 Visor, Assault Pistol, DA CC Weapon(PS=7)" },
    { id: "marspider_engineer", nome: "Marspider (Engineer)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Engineer, CC Attack (+1B), Climbing Plus, Courage, Dodge (+1\"), Martial Arts L1, Stealth, Terrain (Zero-G)", weapon: "Heavy Flamethrower(+1B), Flash Pulse, Panzerfaust", equip: "360 Visor, GizmoKit, Assault Pistol, DA CC Weapon(PS=7)" },
    { id: "marspider_paramedic", nome: "Marspider (Paramedic)", tipo: "LI", mov: "6-2", cc: 23, bs: 11, ph: 13, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Paramedic, CC Attack (+1B), Climbing Plus, Courage, Dodge (+1\"), Martial Arts L1, Stealth, Terrain (Zero-G)", weapon: "Heavy Flamethrower(+1B), Flash Pulse", equip: "360 Visor, MediKit, Assault Pistol, DA CC Weapon(PS=7)" },
    { id: "kulak_hrl", nome: "Kulak (Heavy Rocket Launcher)", tipo: "MI", mov: "4-4", cc: 18, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "BS Attack (Shock), Immunity (Shock), Mimetism (-3), Religious Troop, Terrain (Total)", weapon: "Heavy Rocket Launcher, Pulzar(+1B)", equip: "MULTI Pistol, CC Weapon" },
    { id: "kulak_hacker", nome: "Kulak (Hacker, Killer Hacking Device)", tipo: "MI", mov: "4-4", cc: 18, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, BS Attack (Shock), Immunity (Shock), Mimetism (-3), Religious Troop, Terrain (Total)", weapon: "AP Submachine Gun, D-Charges, Cybermine, Disco Baller", equip: "Killer Hacking Device (UPGRADE Carbonite), Pistol, CC Weapon" },
    { id: "kulak_combi", nome: "Kulak (Combi Rifle)", tipo: "MI", mov: "4-4", cc: 18, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "BS Attack (Shock), Immunity (Shock), Mimetism (-3), Religious Troop, Terrain (Total)", weapon: "Combi Rifle(+1B), Pulzar", equip: "MULTI Pistol, CC Weapon" },
    { id: "kulak_cmd", nome: "Kulak (Chain of Command)", tipo: "MI", mov: "4-4", cc: 18, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Chain of Command, BS Attack (Shock), Immunity (Shock), Mimetism (-3), Religious Troop, Terrain (Total)", weapon: "Boarding Shotgun(+1B), D-Charges", equip: "Pistol, CC Weapon" },
    { id: "kulak_fo", nome: "Kulak (Forward Observer)", tipo: "MI", mov: "4-4", cc: 18, bs: 13, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Forward Observer, BS Attack (Shock), Immunity (Shock), Mimetism (-3), Religious Troop, Terrain (Total)", weapon: "Boarding Shotgun(+1B), Flash Pulse, D-Charges", equip: "Pistol, CC Weapon" },
    { id: "rounder", nome: "Rounder (MULTI Marksman Rifle)", tipo: "MI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Marksmanship, NCO, Terrain (Zero-G)", weapon: "MULTI Marksman Rifle", equip: "Biometric Visor, Multispectral Visor L1, Boarding Pistol, CC Weapon" },
    { id: "rounder_redfury", nome: "Rounder (Red Fury)", tipo: "MI", mov: "4-4", cc: 17, bs: 12, ph: 10, wip: 13, arm: 1, bts: 3, w: 1, s: 2, skills: "Marksmanship, NCO, Terrain (Zero-G)", weapon: "Red Fury", equip: "Biometric Visor, Multispectral Visor L1, Boarding Pistol, CC Weapon" },

    // ===== GRUPPI 2 / 9 / 17 / 18 — profili aggiunti dal PDF ufficiale =====
    { id: "zondnautica_c", nome: "Zondnautica-C (Hacker, Hacking Device)", tipo: "MI", mov: "8-4", cc: 15, bs: 12, ph: 12, wip: 13, arm: 3, bts: 3, w: 1, s: 4, skills: "Hacker, Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Combi Rifle, Chain Rifle, Smoke Grenade Launcher, Flash Pulse", equip: "AI Motorcycle, Hacking Device, Pistol, CC Weapon" },
    { id: "zondnaut_c", nome: "Zondnaut-C (Hacker, Hacking Device)", tipo: "MI", mov: "4-4", cc: 15, bs: 12, ph: 11, wip: 13, arm: 2, bts: 3, w: 1, s: 2, skills: "Hacker, Courage, Impetuous, Limited Cover, Mimetism (-3), Transmutation (Auto)", weapon: "Combi Rifle, Flash Pulse", equip: "Hacking Device, Pistol, CC Weapon" },
    { id: "zoe_fto", nome: "Zoe FTO (Hacker)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Engineer, Immunity (Shock), Immunity (BTS)", weapon: "Combi Rifle, D-Charges", equip: "Deactivator, GizmoKit(+1B), Hacking Device (UPGRADE Zero Pain), Pistol, PARA CC Weapon(-3)" },
    { id: "zoe_fto2", nome: "Zoe FTO-2 (Hacker)", tipo: "LI", mov: "4-4", cc: 16, bs: 11, ph: 10, wip: 15, arm: 1, bts: 3, w: 1, s: 2, skills: "Hacker, Engineer, Immunity (Shock), Immunity (BTS)", weapon: "Boarding Shotgun, D-Charges", equip: "Deactivator, GizmoKit(+1B), Hacking Device (UPGRADE Zero Pain), Pistol, PARA CC Weapon(-3)" },
    { id: "switcher_fto_bsattack", nome: "Switcher FTO (BS Attack [+1B])", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 0, str: 1, s: 2, skills: "Courage, Dogged, Transmutation (WIP)", weapon: "Thunderbolt, E/M Carbine, E/M Grenades", equip: "Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_fto_bsattack_enh", nome: "Switcher FTO (BS Attack [+1B]) - Enhanced Profile", tipo: "LI", mov: "6-4", cc: 23, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, str: 1, s: 2, skills: "Berserk (+3), Courage, Dodge (+2\"), Dogged, Immunity (BTS), Martial Arts L1", weapon: "Thunderbolt, E/M Carbine, E/M Grenades", equip: "X Visor, Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_fto_combi", nome: "Switcher FTO (Combi Rifle)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 0, str: 1, s: 2, skills: "Courage, Dogged, Transmutation (WIP)", weapon: "Combi Rifle, E/Mitter, Zapper", equip: "Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_fto_combi_enh", nome: "Switcher FTO (Combi Rifle) - Enhanced Profile", tipo: "LI", mov: "6-4", cc: 23, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, str: 1, s: 2, skills: "Berserk (+3), Courage, Dodge (+2\"), Dogged, Immunity (BTS), Martial Arts L1", weapon: "Combi Rifle, E/Mitter, Zapper", equip: "X Visor, Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_fto_fo", nome: "Switcher FTO (Forward Observer)", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 0, str: 1, s: 2, skills: "Forward Observer, Courage, Dogged, Transmutation (WIP)", weapon: "AP Submachine Gun, Flash Pulse(+1B), E/M Grenades", equip: "Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_fto_fo_enh", nome: "Switcher FTO (Forward Observer) - Enhanced Profile", tipo: "LI", mov: "6-4", cc: 23, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, str: 1, s: 2, skills: "Forward Observer, Berserk (+3), Courage, Dodge (+2\"), Dogged, Immunity (BTS), Martial Arts L1", weapon: "AP Submachine Gun, Flash Pulse(+1B), E/M Grenades", equip: "X Visor, Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher", nome: "Switcher", tipo: "LI", mov: "4-4", cc: 15, bs: 12, ph: 10, wip: 13, arm: 1, bts: 0, str: 1, s: 2, skills: "Courage, Dogged, Transmutation (WIP)", weapon: "AP Submachine Gun, Flash Pulse(+1B), E/M Grenades, Madtraps", equip: "Pistol, Viral CC Weapon(PS=6)" },
    { id: "switcher_enh", nome: "Switcher - Enhanced Profile", tipo: "LI", mov: "6-4", cc: 23, bs: 13, ph: 14, wip: 13, arm: 3, bts: 3, str: 1, s: 2, skills: "Berserk (+3), Courage, Dodge (+2\"), Dogged, Immunity (BTS), Martial Arts L1", weapon: "AP Submachine Gun, Flash Pulse(+1B), E/M Grenades, Madtraps", equip: "X Visor, Pistol, Viral CC Weapon(PS=6)" },
    { id: "gecko_pilot", nome: "Gecko Pilot (Terrain [Zero-G])", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Specialist Operative, TAGCom (Dodge (PH+3), GizmoKit (PH+1)), Terrain (Zero-G)", weapon: "Combi Rifle", equip: "GizmoKit, Assault Pistol(+1B), CC Weapon" },
    { id: "szalamandra_pilot", nome: "Szalamandra Pilot (Hacker, Killer Hacking Device)", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Hacker, Specialist Operative, TAGCom (Dodge (PH+3), GizmoKit (PH+1))", weapon: "Light Shotgun, Cybermine", equip: "Killer Hacking Device, Pistol, CC Weapon" },
    { id: "gator_pilot", nome: "Gator Pilot (CC Attack [+9])", tipo: "LI", mov: "4-4", cc: 13, bs: 11, ph: 10, wip: 13, arm: 1, bts: 0, w: 1, s: 2, skills: "Specialist Operative, TAGCom (Dodge (PH+3), GizmoKit (PH+1))", weapon: "Boarding Shotgun, D-Charges", equip: "Kobra Pistol, PARA CC Weapon(-6)" },
    { id: "gopod_hrl", nome: "Go-Pod (BS Attack [SR-1])", tipo: "VH", mov: "8-2", cc: 0, bs: 13, ph: 13, wip: 13, arm: 2, bts: 6, str: 2, s: 7, skills: "Aerial, BS Attack (-3), BS Attack (+1B), Courage, Dodge (-3), Mimetism (-3), No Cover, Super-Jump (Jet Propulsion), Super-Jump (3\"), Terrain (Total)", weapon: "Heavy Rocket Launcher, AP Submachine Gun", equip: "-" },
    { id: "gopod_multi", nome: "Go-Pod (MULTI Rifle)", tipo: "VH", mov: "8-2", cc: 0, bs: 13, ph: 13, wip: 13, arm: 2, bts: 6, str: 2, s: 7, skills: "Aerial, BS Attack (-3), BS Attack (+1B), Courage, Dodge (-3), Mimetism (-3), No Cover, Super-Jump (Jet Propulsion), Super-Jump (3\"), Terrain (Total)", weapon: "MULTI Rifle, E/Mitter", equip: "-" },
    { id: "gobot", nome: "Go-Bot (REM)", tipo: "REM", mov: "8-2", cc: 0, bs: 5, ph: 11, wip: 13, arm: 1, bts: 3, str: 1, s: 2, skills: "Aerial, BS Attack (-3), Courage, Dodge (-3), Mimetism (-3), No Cover, Peripheral (Synchronized), Super-Jump (Jet Propulsion), Super-Jump (3\"), Terrain (Total)", weapon: "Flash Pulse, Chain-colt", equip: "-" },
    { id: "triggermen_sniper", nome: "Triggermen (BS Attack [+1B], MULTI Sniper Rifle)", tipo: "HI", mov: "6-2", cc: 17, bs: 13, ph: 12, wip: 13, arm: 4, bts: 6, w: 2, s: 4, skills: "CC Attack (-3), Immunity (Shock), Mimetism (-3), Regeneration (PH=13), Stealth", weapon: "MULTI Sniper Rifle, E/Marat", equip: "360 Visor, MULTI Pistol, CC Weapon" },
    { id: "triggermen_neuro", nome: "Triggermen (Neurocinetics)", tipo: "HI", mov: "6-2", cc: 17, bs: 13, ph: 12, wip: 13, arm: 4, bts: 6, w: 2, s: 4, skills: "Neurocinetics, CC Attack (-3), Immunity (Shock), Mimetism (-3), Regeneration (PH=13), Stealth", weapon: "MULTI Sniper Rifle, E/Marat", equip: "360 Visor, MULTI Pistol, CC Weapon" },
    { id: "triggermen_multi", nome: "Triggermen (BS Attack [+1B], MULTI Rifle)", tipo: "HI", mov: "6-2", cc: 17, bs: 13, ph: 12, wip: 13, arm: 4, bts: 6, w: 2, s: 4, skills: "CC Attack (-3), Immunity (Shock), Mimetism (-3), Regeneration (PH=13), Stealth", weapon: "MULTI Rifle, E/Marat", equip: "360 Visor, MULTI Pistol, CC Weapon" },
    { id: "triggermen_fd", nome: "Triggermen (BS Attack [+1B], Forward Deployment [+4\"])", tipo: "HI", mov: "6-2", cc: 17, bs: 13, ph: 12, wip: 13, arm: 4, bts: 6, w: 2, s: 4, skills: "Forward Deployment (+4\"), CC Attack (-3), Immunity (Shock), Mimetism (-3), Regeneration (PH=13), Stealth", weapon: "K1 Combi Rifle, E/Marat", equip: "360 Visor, MULTI Pistol, Silenced Pistol, CC Weapon" }
];


// Dichiarazione di versione per il controllo incrociato fra chat.
// UN SOLO punto in cui il numero e` scritto: la riga @versione in testa al file.
// Qui non viene ripetuto, viene LETTO da li`, cosi` non possono divergere.
// Funziona anche se questo file si carica PRIMA del motore: in quel caso la
// versione resta in coda e il motore la raccoglie all'avvio.
(function () {
    var g = (typeof window !== 'undefined') ? window : globalThis;
    var FILE = 'database_nomad.js';
    var vers = null;

    // Node / test: leggo l'intestazione dal sorgente stesso.
    try {
        if (typeof require === 'function' && typeof __filename === 'string') {
            var testa = require('fs').readFileSync(__filename, 'utf8').slice(0, 200);
            var m = testa.match(/@versione\s+(\S+)/);
            if (m) vers = m[1];
        }
    } catch (e) { /* ambiente senza fs: si passa al ramo browser */ }

    // Browser: l'intestazione non e` leggibile a runtime. Il motore la ricava
    // dal sorgente gia` caricato; se non ci riesce resta null e viene segnalata
    // come "da verificare" invece di essere data per buona.
    if (!vers && g.MotoreN5 && g.MotoreN5.versioneDaIntestazione)
        vers = g.MotoreN5.versioneDaIntestazione(FILE);

    var v = { file: FILE, versione: vers, proprieta: 'DATABASE' };
    if (g.MotoreN5 && g.MotoreN5.dichiaraVersione) g.MotoreN5.dichiaraVersione(v.file, v.versione, v.proprieta);
    else { g.__versioniN5 = g.__versioniN5 || []; g.__versioniN5.push(v); }
})();
